'''
    This code was AUTOGENERATED using the codama library.
    Please DO NOT EDIT THIS FILE, instead use visitors
    to add features, then rerun codama to update it.
    @see https://github.com/codama-idl/codama
'''

from . import assetTier
from .assetTier import AssetTierJSON,AssetTierKind;
from . import bigFractionBytes
from .bigFractionBytes import BigFractionBytesJSON,BigFractionBytes;
from . import borrowRateCurve
from .borrowRateCurve import BorrowRateCurveJSON,BorrowRateCurve;
from . import curvePoint
from .curvePoint import CurvePointJSON,CurvePoint;
from . import elevationGroup
from .elevationGroup import ElevationGroupJSON,ElevationGroup;
from . import feeCalculation
from .feeCalculation import FeeCalculationJSON,FeeCalculationKind;
from . import lastUpdate
from .lastUpdate import LastUpdateJSON,LastUpdate;
from . import obligationCollateral
from .obligationCollateral import ObligationCollateralJSON,ObligationCollateral;
from . import obligationLiquidity
from .obligationLiquidity import ObligationLiquidityJSON,ObligationLiquidity;
from . import obligationOrder
from .obligationOrder import ObligationOrderJSON,ObligationOrder;
from . import priceHeuristic
from .priceHeuristic import PriceHeuristicJSON,PriceHeuristic;
from . import pythConfiguration
from .pythConfiguration import PythConfigurationJSON,PythConfiguration;
from . import reserveCollateral
from .reserveCollateral import ReserveCollateralJSON,ReserveCollateral;
from . import reserveConfig
from .reserveConfig import ReserveConfigJSON,ReserveConfig;
from . import reserveFarmKind
from .reserveFarmKind import ReserveFarmKindJSON,ReserveFarmKindKind;
from . import reserveFees
from .reserveFees import ReserveFeesJSON,ReserveFees;
from . import reserveLiquidity
from .reserveLiquidity import ReserveLiquidityJSON,ReserveLiquidity;
from . import reserveStatus
from .reserveStatus import ReserveStatusJSON,ReserveStatusKind;
from . import scopeConfiguration
from .scopeConfiguration import ScopeConfigurationJSON,ScopeConfiguration;
from . import switchboardConfiguration
from .switchboardConfiguration import SwitchboardConfigurationJSON,SwitchboardConfiguration;
from . import tokenInfo
from .tokenInfo import TokenInfoJSON,TokenInfo;
from . import updateConfigMode
from .updateConfigMode import UpdateConfigModeJSON,UpdateConfigModeKind;
from . import updateLendingMarketConfigValue
from .updateLendingMarketConfigValue import UpdateLendingMarketConfigValueJSON,UpdateLendingMarketConfigValueKind;
from . import updateLendingMarketMode
from .updateLendingMarketMode import UpdateLendingMarketModeJSON,UpdateLendingMarketModeKind;
from . import withdrawalCaps
from .withdrawalCaps import WithdrawalCapsJSON,WithdrawalCaps;
