'''
    This code was AUTOGENERATED using the codama library.
    Please DO NOT EDIT THIS FILE, instead use visitors
    to add features, then rerun codama to update it.
    @see https://github.com/codama-idl/codama
'''

import borsh_construct as borsh
import typing
from construct import Container
from dataclasses import dataclass
from . import curvePoint

class BorrowRateCurveJSON(typing.TypedDict):
    points: list[curvePoint.CurvePointJSON]

@dataclass
class BorrowRateCurve:
    layout: typing.ClassVar = borsh.CStruct(
        "points" /curvePoint.CurvePoint.layout[11],
        )
    #fields
    points: list[curvePoint.CurvePoint]
    
    @classmethod
    def from_decoded(cls, obj: Container) -> "BorrowRateCurve":
        return cls(
        points=list(map(lambda item:curvePoint.CurvePoint.from_json(item),obj["points"])),
        )

    def to_encodable(self) -> dict[str, typing.Any]:
        return {
                "points": self.points,
                }

    def to_json(self) -> BorrowRateCurveJSON:
        return {
                "points": list(map(lambda item:item.to_json(),self.points)),
                }

    @classmethod
    def from_json(cls, obj: BorrowRateCurveJSON) -> "BorrowRateCurve":
        return cls(
                points=list(map(lambda item:curvePoint.CurvePoint.from_json(item),obj["points"])),
        )






