'''
    This code was AUTOGENERATED using the codama library.
    Please DO NOT EDIT THIS FILE, instead use visitors
    to add features, then rerun codama to update it.
    @see https://github.com/codama-idl/codama
'''

import borsh_construct as borsh
import typing
from construct import Container
from dataclasses import dataclass

class CurvePointJSON(typing.TypedDict):
    utilizationRateBps: int
    borrowRateBps: int

@dataclass
class CurvePoint:
    layout: typing.ClassVar = borsh.CStruct(
        "utilizationRateBps" /borsh.U32,
        "borrowRateBps" /borsh.U32,
        )
    #fields
    utilizationRateBps: int
    borrowRateBps: int
    
    @classmethod
    def from_decoded(cls, obj: Container) -> "CurvePoint":
        return cls(
        utilizationRateBps=obj["utilizationRateBps"],
        borrowRateBps=obj["borrowRateBps"],
        )

    def to_encodable(self) -> dict[str, typing.Any]:
        return {
                "utilizationRateBps": self.utilizationRateBps,
                "borrowRateBps": self.borrowRateBps,
                }

    def to_json(self) -> CurvePointJSON:
        return {
                "utilizationRateBps": self.utilizationRateBps,
                "borrowRateBps": self.borrowRateBps,
                }

    @classmethod
    def from_json(cls, obj: CurvePointJSON) -> "CurvePoint":
        return cls(
                utilizationRateBps=obj["utilizationRateBps"],
                borrowRateBps=obj["borrowRateBps"],
        )






