'''
    This code was AUTOGENERATED using the codama library.
    Please DO NOT EDIT THIS FILE, instead use visitors
    to add features, then rerun codama to update it.
    @see https://github.com/codama-idl/codama
'''

import borsh_construct as borsh
import typing
from construct import Container
from dataclasses import dataclass

class LastUpdateJSON(typing.TypedDict):
    slot: int
    stale: int
    priceStatus: int
    placeholder: list[int]

@dataclass
class LastUpdate:
    layout: typing.ClassVar = borsh.CStruct(
        "slot" /borsh.U64,
        "stale" /borsh.U8,
        "priceStatus" /borsh.U8,
        "placeholder" /borsh.U8[6],
        )
    #fields
    slot: int
    stale: int
    priceStatus: int
    placeholder: list[int]
    
    @classmethod
    def from_decoded(cls, obj: Container) -> "LastUpdate":
        return cls(
        slot=obj["slot"],
        stale=obj["stale"],
        priceStatus=obj["priceStatus"],
        placeholder=obj["placeholder"],
        )

    def to_encodable(self) -> dict[str, typing.Any]:
        return {
                "slot": self.slot,
                "stale": self.stale,
                "priceStatus": self.priceStatus,
                "placeholder": self.placeholder,
                }

    def to_json(self) -> LastUpdateJSON:
        return {
                "slot": self.slot,
                "stale": self.stale,
                "priceStatus": self.priceStatus,
                "placeholder": self.placeholder,
                }

    @classmethod
    def from_json(cls, obj: LastUpdateJSON) -> "LastUpdate":
        return cls(
                slot=obj["slot"],
                stale=obj["stale"],
                priceStatus=obj["priceStatus"],
                placeholder=obj["placeholder"],
        )






