'''
    This code was AUTOGENERATED using the codama library.
    Please DO NOT EDIT THIS FILE, instead use visitors
    to add features, then rerun codama to update it.
    @see https://github.com/codama-idl/codama
'''

import borsh_construct as borsh
import typing
from construct import Container
from dataclasses import dataclass

class PriceHeuristicJSON(typing.TypedDict):
    lower: int
    upper: int
    exp: int

@dataclass
class PriceHeuristic:
    layout: typing.ClassVar = borsh.CStruct(
        "lower" /borsh.U64,
        "upper" /borsh.U64,
        "exp" /borsh.U64,
        )
    #fields
    lower: int
    upper: int
    exp: int
    
    @classmethod
    def from_decoded(cls, obj: Container) -> "PriceHeuristic":
        return cls(
        lower=obj["lower"],
        upper=obj["upper"],
        exp=obj["exp"],
        )

    def to_encodable(self) -> dict[str, typing.Any]:
        return {
                "lower": self.lower,
                "upper": self.upper,
                "exp": self.exp,
                }

    def to_json(self) -> PriceHeuristicJSON:
        return {
                "lower": self.lower,
                "upper": self.upper,
                "exp": self.exp,
                }

    @classmethod
    def from_json(cls, obj: PriceHeuristicJSON) -> "PriceHeuristic":
        return cls(
                lower=obj["lower"],
                upper=obj["upper"],
                exp=obj["exp"],
        )






