'''
    This code was AUTOGENERATED using the codama library.
    Please DO NOT EDIT THIS FILE, instead use visitors
    to add features, then rerun codama to update it.
    @see https://github.com/codama-idl/codama
'''

import borsh_construct as borsh
import typing
from construct import Container
from dataclasses import dataclass

class ReserveFeesJSON(typing.TypedDict):
    borrowFeeSf: int
    flashLoanFeeSf: int
    padding: list[int]

@dataclass
class ReserveFees:
    layout: typing.ClassVar = borsh.CStruct(
        "borrowFeeSf" /borsh.U64,
        "flashLoanFeeSf" /borsh.U64,
        "padding" /borsh.U8[8],
        )
    #fields
    borrowFeeSf: int
    flashLoanFeeSf: int
    padding: list[int]
    
    @classmethod
    def from_decoded(cls, obj: Container) -> "ReserveFees":
        return cls(
        borrowFeeSf=obj["borrowFeeSf"],
        flashLoanFeeSf=obj["flashLoanFeeSf"],
        padding=obj["padding"],
        )

    def to_encodable(self) -> dict[str, typing.Any]:
        return {
                "borrowFeeSf": self.borrowFeeSf,
                "flashLoanFeeSf": self.flashLoanFeeSf,
                "padding": self.padding,
                }

    def to_json(self) -> ReserveFeesJSON:
        return {
                "borrowFeeSf": self.borrowFeeSf,
                "flashLoanFeeSf": self.flashLoanFeeSf,
                "padding": self.padding,
                }

    @classmethod
    def from_json(cls, obj: ReserveFeesJSON) -> "ReserveFees":
        return cls(
                borrowFeeSf=obj["borrowFeeSf"],
                flashLoanFeeSf=obj["flashLoanFeeSf"],
                padding=obj["padding"],
        )






