'''
    This code was AUTOGENERATED using the codama library.
    Please DO NOT EDIT THIS FILE, instead use visitors
    to add features, then rerun codama to update it.
    @see https://github.com/codama-idl/codama
'''

import borsh_construct as borsh
import typing
from anchorpy.borsh_extension import BorshPubkey
from construct import Container
from dataclasses import dataclass
from solders.pubkey import Pubkey as SolPubkey

class ScopeConfigurationJSON(typing.TypedDict):
    priceFeed: str
    priceChain: list[int]
    twapChain: list[int]

@dataclass
class ScopeConfiguration:
    layout: typing.ClassVar = borsh.CStruct(
        "priceFeed" /BorshPubkey,
        "priceChain" /borsh.U16[4],
        "twapChain" /borsh.U16[4],
        )
    #fields
    priceFeed: SolPubkey
    priceChain: list[int]
    twapChain: list[int]
    
    @classmethod
    def from_decoded(cls, obj: Container) -> "ScopeConfiguration":
        return cls(
        priceFeed=obj["priceFeed"],
        priceChain=obj["priceChain"],
        twapChain=obj["twapChain"],
        )

    def to_encodable(self) -> dict[str, typing.Any]:
        return {
                "priceFeed": self.priceFeed,
                "priceChain": self.priceChain,
                "twapChain": self.twapChain,
                }

    def to_json(self) -> ScopeConfigurationJSON:
        return {
                "priceFeed": str(self.priceFeed),
                "priceChain": self.priceChain,
                "twapChain": self.twapChain,
                }

    @classmethod
    def from_json(cls, obj: ScopeConfigurationJSON) -> "ScopeConfiguration":
        return cls(
                priceFeed=SolPubkey.from_string(obj["priceFeed"]),
                priceChain=obj["priceChain"],
                twapChain=obj["twapChain"],
        )






