'''
    This code was AUTOGENERATED using the codama library.
    Please DO NOT EDIT THIS FILE, instead use visitors
    to add features, then rerun codama to update it.
    @see https://github.com/codama-idl/codama
'''

import borsh_construct as borsh
import typing
from anchorpy.borsh_extension import EnumForCodegen
from dataclasses import dataclass


class UpdateOwnerJSON(typing.TypedDict):
    kind: typing.Literal["UpdateOwner"]


@dataclass
class UpdateOwner:
    discriminator: typing.ClassVar = 0
    def to_json(self) -> UpdateOwnerJSON:
        return UpdateOwnerJSON(
            kind="UpdateOwner",
        )

    def to_encodable(self) -> dict[str, typing.Any]:
        return {
            "UpdateOwner": {},
        }




class UpdateEmergencyModeJSON(typing.TypedDict):
    kind: typing.Literal["UpdateEmergencyMode"]


@dataclass
class UpdateEmergencyMode:
    discriminator: typing.ClassVar = 1
    def to_json(self) -> UpdateEmergencyModeJSON:
        return UpdateEmergencyModeJSON(
            kind="UpdateEmergencyMode",
        )

    def to_encodable(self) -> dict[str, typing.Any]:
        return {
            "UpdateEmergencyMode": {},
        }




class UpdateLiquidationCloseFactorJSON(typing.TypedDict):
    kind: typing.Literal["UpdateLiquidationCloseFactor"]


@dataclass
class UpdateLiquidationCloseFactor:
    discriminator: typing.ClassVar = 2
    def to_json(self) -> UpdateLiquidationCloseFactorJSON:
        return UpdateLiquidationCloseFactorJSON(
            kind="UpdateLiquidationCloseFactor",
        )

    def to_encodable(self) -> dict[str, typing.Any]:
        return {
            "UpdateLiquidationCloseFactor": {},
        }




class UpdateLiquidationMaxValueJSON(typing.TypedDict):
    kind: typing.Literal["UpdateLiquidationMaxValue"]


@dataclass
class UpdateLiquidationMaxValue:
    discriminator: typing.ClassVar = 3
    def to_json(self) -> UpdateLiquidationMaxValueJSON:
        return UpdateLiquidationMaxValueJSON(
            kind="UpdateLiquidationMaxValue",
        )

    def to_encodable(self) -> dict[str, typing.Any]:
        return {
            "UpdateLiquidationMaxValue": {},
        }




class DeprecatedUpdateGlobalUnhealthyBorrowJSON(typing.TypedDict):
    kind: typing.Literal["DeprecatedUpdateGlobalUnhealthyBorrow"]


@dataclass
class DeprecatedUpdateGlobalUnhealthyBorrow:
    discriminator: typing.ClassVar = 4
    def to_json(self) -> DeprecatedUpdateGlobalUnhealthyBorrowJSON:
        return DeprecatedUpdateGlobalUnhealthyBorrowJSON(
            kind="DeprecatedUpdateGlobalUnhealthyBorrow",
        )

    def to_encodable(self) -> dict[str, typing.Any]:
        return {
            "DeprecatedUpdateGlobalUnhealthyBorrow": {},
        }




class UpdateGlobalAllowedBorrowJSON(typing.TypedDict):
    kind: typing.Literal["UpdateGlobalAllowedBorrow"]


@dataclass
class UpdateGlobalAllowedBorrow:
    discriminator: typing.ClassVar = 5
    def to_json(self) -> UpdateGlobalAllowedBorrowJSON:
        return UpdateGlobalAllowedBorrowJSON(
            kind="UpdateGlobalAllowedBorrow",
        )

    def to_encodable(self) -> dict[str, typing.Any]:
        return {
            "UpdateGlobalAllowedBorrow": {},
        }




class UpdateRiskCouncilJSON(typing.TypedDict):
    kind: typing.Literal["UpdateRiskCouncil"]


@dataclass
class UpdateRiskCouncil:
    discriminator: typing.ClassVar = 6
    def to_json(self) -> UpdateRiskCouncilJSON:
        return UpdateRiskCouncilJSON(
            kind="UpdateRiskCouncil",
        )

    def to_encodable(self) -> dict[str, typing.Any]:
        return {
            "UpdateRiskCouncil": {},
        }




class UpdateMinFullLiquidationThresholdJSON(typing.TypedDict):
    kind: typing.Literal["UpdateMinFullLiquidationThreshold"]


@dataclass
class UpdateMinFullLiquidationThreshold:
    discriminator: typing.ClassVar = 7
    def to_json(self) -> UpdateMinFullLiquidationThresholdJSON:
        return UpdateMinFullLiquidationThresholdJSON(
            kind="UpdateMinFullLiquidationThreshold",
        )

    def to_encodable(self) -> dict[str, typing.Any]:
        return {
            "UpdateMinFullLiquidationThreshold": {},
        }




class UpdateInsolvencyRiskLtvJSON(typing.TypedDict):
    kind: typing.Literal["UpdateInsolvencyRiskLtv"]


@dataclass
class UpdateInsolvencyRiskLtv:
    discriminator: typing.ClassVar = 8
    def to_json(self) -> UpdateInsolvencyRiskLtvJSON:
        return UpdateInsolvencyRiskLtvJSON(
            kind="UpdateInsolvencyRiskLtv",
        )

    def to_encodable(self) -> dict[str, typing.Any]:
        return {
            "UpdateInsolvencyRiskLtv": {},
        }




class UpdateElevationGroupJSON(typing.TypedDict):
    kind: typing.Literal["UpdateElevationGroup"]


@dataclass
class UpdateElevationGroup:
    discriminator: typing.ClassVar = 9
    def to_json(self) -> UpdateElevationGroupJSON:
        return UpdateElevationGroupJSON(
            kind="UpdateElevationGroup",
        )

    def to_encodable(self) -> dict[str, typing.Any]:
        return {
            "UpdateElevationGroup": {},
        }




class UpdateReferralFeeBpsJSON(typing.TypedDict):
    kind: typing.Literal["UpdateReferralFeeBps"]


@dataclass
class UpdateReferralFeeBps:
    discriminator: typing.ClassVar = 10
    def to_json(self) -> UpdateReferralFeeBpsJSON:
        return UpdateReferralFeeBpsJSON(
            kind="UpdateReferralFeeBps",
        )

    def to_encodable(self) -> dict[str, typing.Any]:
        return {
            "UpdateReferralFeeBps": {},
        }




class DeprecatedUpdateMultiplierPointsJSON(typing.TypedDict):
    kind: typing.Literal["DeprecatedUpdateMultiplierPoints"]


@dataclass
class DeprecatedUpdateMultiplierPoints:
    discriminator: typing.ClassVar = 11
    def to_json(self) -> DeprecatedUpdateMultiplierPointsJSON:
        return DeprecatedUpdateMultiplierPointsJSON(
            kind="DeprecatedUpdateMultiplierPoints",
        )

    def to_encodable(self) -> dict[str, typing.Any]:
        return {
            "DeprecatedUpdateMultiplierPoints": {},
        }




class UpdatePriceRefreshTriggerToMaxAgePctJSON(typing.TypedDict):
    kind: typing.Literal["UpdatePriceRefreshTriggerToMaxAgePct"]


@dataclass
class UpdatePriceRefreshTriggerToMaxAgePct:
    discriminator: typing.ClassVar = 12
    def to_json(self) -> UpdatePriceRefreshTriggerToMaxAgePctJSON:
        return UpdatePriceRefreshTriggerToMaxAgePctJSON(
            kind="UpdatePriceRefreshTriggerToMaxAgePct",
        )

    def to_encodable(self) -> dict[str, typing.Any]:
        return {
            "UpdatePriceRefreshTriggerToMaxAgePct": {},
        }




class UpdateAutodeleverageEnabledJSON(typing.TypedDict):
    kind: typing.Literal["UpdateAutodeleverageEnabled"]


@dataclass
class UpdateAutodeleverageEnabled:
    discriminator: typing.ClassVar = 13
    def to_json(self) -> UpdateAutodeleverageEnabledJSON:
        return UpdateAutodeleverageEnabledJSON(
            kind="UpdateAutodeleverageEnabled",
        )

    def to_encodable(self) -> dict[str, typing.Any]:
        return {
            "UpdateAutodeleverageEnabled": {},
        }




class UpdateBorrowingDisabledJSON(typing.TypedDict):
    kind: typing.Literal["UpdateBorrowingDisabled"]


@dataclass
class UpdateBorrowingDisabled:
    discriminator: typing.ClassVar = 14
    def to_json(self) -> UpdateBorrowingDisabledJSON:
        return UpdateBorrowingDisabledJSON(
            kind="UpdateBorrowingDisabled",
        )

    def to_encodable(self) -> dict[str, typing.Any]:
        return {
            "UpdateBorrowingDisabled": {},
        }




class UpdateMinNetValueObligationPostActionJSON(typing.TypedDict):
    kind: typing.Literal["UpdateMinNetValueObligationPostAction"]


@dataclass
class UpdateMinNetValueObligationPostAction:
    discriminator: typing.ClassVar = 15
    def to_json(self) -> UpdateMinNetValueObligationPostActionJSON:
        return UpdateMinNetValueObligationPostActionJSON(
            kind="UpdateMinNetValueObligationPostAction",
        )

    def to_encodable(self) -> dict[str, typing.Any]:
        return {
            "UpdateMinNetValueObligationPostAction": {},
        }




class UpdateMinValueLtvSkipPriorityLiqCheckJSON(typing.TypedDict):
    kind: typing.Literal["UpdateMinValueLtvSkipPriorityLiqCheck"]


@dataclass
class UpdateMinValueLtvSkipPriorityLiqCheck:
    discriminator: typing.ClassVar = 16
    def to_json(self) -> UpdateMinValueLtvSkipPriorityLiqCheckJSON:
        return UpdateMinValueLtvSkipPriorityLiqCheckJSON(
            kind="UpdateMinValueLtvSkipPriorityLiqCheck",
        )

    def to_encodable(self) -> dict[str, typing.Any]:
        return {
            "UpdateMinValueLtvSkipPriorityLiqCheck": {},
        }




class UpdateMinValueBfSkipPriorityLiqCheckJSON(typing.TypedDict):
    kind: typing.Literal["UpdateMinValueBfSkipPriorityLiqCheck"]


@dataclass
class UpdateMinValueBfSkipPriorityLiqCheck:
    discriminator: typing.ClassVar = 17
    def to_json(self) -> UpdateMinValueBfSkipPriorityLiqCheckJSON:
        return UpdateMinValueBfSkipPriorityLiqCheckJSON(
            kind="UpdateMinValueBfSkipPriorityLiqCheck",
        )

    def to_encodable(self) -> dict[str, typing.Any]:
        return {
            "UpdateMinValueBfSkipPriorityLiqCheck": {},
        }




class UpdatePaddingFieldsJSON(typing.TypedDict):
    kind: typing.Literal["UpdatePaddingFields"]


@dataclass
class UpdatePaddingFields:
    discriminator: typing.ClassVar = 18
    def to_json(self) -> UpdatePaddingFieldsJSON:
        return UpdatePaddingFieldsJSON(
            kind="UpdatePaddingFields",
        )

    def to_encodable(self) -> dict[str, typing.Any]:
        return {
            "UpdatePaddingFields": {},
        }




class UpdateNameJSON(typing.TypedDict):
    kind: typing.Literal["UpdateName"]


@dataclass
class UpdateName:
    discriminator: typing.ClassVar = 19
    def to_json(self) -> UpdateNameJSON:
        return UpdateNameJSON(
            kind="UpdateName",
        )

    def to_encodable(self) -> dict[str, typing.Any]:
        return {
            "UpdateName": {},
        }




class UpdateIndividualAutodeleverageMarginCallPeriodSecsJSON(typing.TypedDict):
    kind: typing.Literal["UpdateIndividualAutodeleverageMarginCallPeriodSecs"]


@dataclass
class UpdateIndividualAutodeleverageMarginCallPeriodSecs:
    discriminator: typing.ClassVar = 20
    def to_json(self) -> UpdateIndividualAutodeleverageMarginCallPeriodSecsJSON:
        return UpdateIndividualAutodeleverageMarginCallPeriodSecsJSON(
            kind="UpdateIndividualAutodeleverageMarginCallPeriodSecs",
        )

    def to_encodable(self) -> dict[str, typing.Any]:
        return {
            "UpdateIndividualAutodeleverageMarginCallPeriodSecs": {},
        }




class UpdateInitialDepositAmountJSON(typing.TypedDict):
    kind: typing.Literal["UpdateInitialDepositAmount"]


@dataclass
class UpdateInitialDepositAmount:
    discriminator: typing.ClassVar = 21
    def to_json(self) -> UpdateInitialDepositAmountJSON:
        return UpdateInitialDepositAmountJSON(
            kind="UpdateInitialDepositAmount",
        )

    def to_encodable(self) -> dict[str, typing.Any]:
        return {
            "UpdateInitialDepositAmount": {},
        }




class UpdateObligationOrdersEnabledJSON(typing.TypedDict):
    kind: typing.Literal["UpdateObligationOrdersEnabled"]


@dataclass
class UpdateObligationOrdersEnabled:
    discriminator: typing.ClassVar = 22
    def to_json(self) -> UpdateObligationOrdersEnabledJSON:
        return UpdateObligationOrdersEnabledJSON(
            kind="UpdateObligationOrdersEnabled",
        )

    def to_encodable(self) -> dict[str, typing.Any]:
        return {
            "UpdateObligationOrdersEnabled": {},
        }





UpdateLendingMarketModeKind = typing.Union[
    UpdateOwner,
    UpdateEmergencyMode,
    UpdateLiquidationCloseFactor,
    UpdateLiquidationMaxValue,
    DeprecatedUpdateGlobalUnhealthyBorrow,
    UpdateGlobalAllowedBorrow,
    UpdateRiskCouncil,
    UpdateMinFullLiquidationThreshold,
    UpdateInsolvencyRiskLtv,
    UpdateElevationGroup,
    UpdateReferralFeeBps,
    DeprecatedUpdateMultiplierPoints,
    UpdatePriceRefreshTriggerToMaxAgePct,
    UpdateAutodeleverageEnabled,
    UpdateBorrowingDisabled,
    UpdateMinNetValueObligationPostAction,
    UpdateMinValueLtvSkipPriorityLiqCheck,
    UpdateMinValueBfSkipPriorityLiqCheck,
    UpdatePaddingFields,
    UpdateName,
    UpdateIndividualAutodeleverageMarginCallPeriodSecs,
    UpdateInitialDepositAmount,
    UpdateObligationOrdersEnabled,
]
UpdateLendingMarketModeJSON = typing.Union[
    UpdateOwnerJSON,
    UpdateEmergencyModeJSON,
    UpdateLiquidationCloseFactorJSON,
    UpdateLiquidationMaxValueJSON,
    DeprecatedUpdateGlobalUnhealthyBorrowJSON,
    UpdateGlobalAllowedBorrowJSON,
    UpdateRiskCouncilJSON,
    UpdateMinFullLiquidationThresholdJSON,
    UpdateInsolvencyRiskLtvJSON,
    UpdateElevationGroupJSON,
    UpdateReferralFeeBpsJSON,
    DeprecatedUpdateMultiplierPointsJSON,
    UpdatePriceRefreshTriggerToMaxAgePctJSON,
    UpdateAutodeleverageEnabledJSON,
    UpdateBorrowingDisabledJSON,
    UpdateMinNetValueObligationPostActionJSON,
    UpdateMinValueLtvSkipPriorityLiqCheckJSON,
    UpdateMinValueBfSkipPriorityLiqCheckJSON,
    UpdatePaddingFieldsJSON,
    UpdateNameJSON,
    UpdateIndividualAutodeleverageMarginCallPeriodSecsJSON,
    UpdateInitialDepositAmountJSON,
    UpdateObligationOrdersEnabledJSON,
]

def from_decoded(obj: dict) -> UpdateLendingMarketModeKind:
    if not isinstance(obj, dict):
        raise ValueError("Invalid enum object")
    if "UpdateOwner" in obj:
      return UpdateOwner()
    if "UpdateEmergencyMode" in obj:
      return UpdateEmergencyMode()
    if "UpdateLiquidationCloseFactor" in obj:
      return UpdateLiquidationCloseFactor()
    if "UpdateLiquidationMaxValue" in obj:
      return UpdateLiquidationMaxValue()
    if "DeprecatedUpdateGlobalUnhealthyBorrow" in obj:
      return DeprecatedUpdateGlobalUnhealthyBorrow()
    if "UpdateGlobalAllowedBorrow" in obj:
      return UpdateGlobalAllowedBorrow()
    if "UpdateRiskCouncil" in obj:
      return UpdateRiskCouncil()
    if "UpdateMinFullLiquidationThreshold" in obj:
      return UpdateMinFullLiquidationThreshold()
    if "UpdateInsolvencyRiskLtv" in obj:
      return UpdateInsolvencyRiskLtv()
    if "UpdateElevationGroup" in obj:
      return UpdateElevationGroup()
    if "UpdateReferralFeeBps" in obj:
      return UpdateReferralFeeBps()
    if "DeprecatedUpdateMultiplierPoints" in obj:
      return DeprecatedUpdateMultiplierPoints()
    if "UpdatePriceRefreshTriggerToMaxAgePct" in obj:
      return UpdatePriceRefreshTriggerToMaxAgePct()
    if "UpdateAutodeleverageEnabled" in obj:
      return UpdateAutodeleverageEnabled()
    if "UpdateBorrowingDisabled" in obj:
      return UpdateBorrowingDisabled()
    if "UpdateMinNetValueObligationPostAction" in obj:
      return UpdateMinNetValueObligationPostAction()
    if "UpdateMinValueLtvSkipPriorityLiqCheck" in obj:
      return UpdateMinValueLtvSkipPriorityLiqCheck()
    if "UpdateMinValueBfSkipPriorityLiqCheck" in obj:
      return UpdateMinValueBfSkipPriorityLiqCheck()
    if "UpdatePaddingFields" in obj:
      return UpdatePaddingFields()
    if "UpdateName" in obj:
      return UpdateName()
    if "UpdateIndividualAutodeleverageMarginCallPeriodSecs" in obj:
      return UpdateIndividualAutodeleverageMarginCallPeriodSecs()
    if "UpdateInitialDepositAmount" in obj:
      return UpdateInitialDepositAmount()
    if "UpdateObligationOrdersEnabled" in obj:
      return UpdateObligationOrdersEnabled()
    raise ValueError("Invalid enum object")

def from_json(obj: UpdateLendingMarketModeJSON) -> UpdateLendingMarketModeKind:
    if obj["kind"] == "UpdateOwner":
        return UpdateOwner()

    if obj["kind"] == "UpdateEmergencyMode":
        return UpdateEmergencyMode()

    if obj["kind"] == "UpdateLiquidationCloseFactor":
        return UpdateLiquidationCloseFactor()

    if obj["kind"] == "UpdateLiquidationMaxValue":
        return UpdateLiquidationMaxValue()

    if obj["kind"] == "DeprecatedUpdateGlobalUnhealthyBorrow":
        return DeprecatedUpdateGlobalUnhealthyBorrow()

    if obj["kind"] == "UpdateGlobalAllowedBorrow":
        return UpdateGlobalAllowedBorrow()

    if obj["kind"] == "UpdateRiskCouncil":
        return UpdateRiskCouncil()

    if obj["kind"] == "UpdateMinFullLiquidationThreshold":
        return UpdateMinFullLiquidationThreshold()

    if obj["kind"] == "UpdateInsolvencyRiskLtv":
        return UpdateInsolvencyRiskLtv()

    if obj["kind"] == "UpdateElevationGroup":
        return UpdateElevationGroup()

    if obj["kind"] == "UpdateReferralFeeBps":
        return UpdateReferralFeeBps()

    if obj["kind"] == "DeprecatedUpdateMultiplierPoints":
        return DeprecatedUpdateMultiplierPoints()

    if obj["kind"] == "UpdatePriceRefreshTriggerToMaxAgePct":
        return UpdatePriceRefreshTriggerToMaxAgePct()

    if obj["kind"] == "UpdateAutodeleverageEnabled":
        return UpdateAutodeleverageEnabled()

    if obj["kind"] == "UpdateBorrowingDisabled":
        return UpdateBorrowingDisabled()

    if obj["kind"] == "UpdateMinNetValueObligationPostAction":
        return UpdateMinNetValueObligationPostAction()

    if obj["kind"] == "UpdateMinValueLtvSkipPriorityLiqCheck":
        return UpdateMinValueLtvSkipPriorityLiqCheck()

    if obj["kind"] == "UpdateMinValueBfSkipPriorityLiqCheck":
        return UpdateMinValueBfSkipPriorityLiqCheck()

    if obj["kind"] == "UpdatePaddingFields":
        return UpdatePaddingFields()

    if obj["kind"] == "UpdateName":
        return UpdateName()

    if obj["kind"] == "UpdateIndividualAutodeleverageMarginCallPeriodSecs":
        return UpdateIndividualAutodeleverageMarginCallPeriodSecs()

    if obj["kind"] == "UpdateInitialDepositAmount":
        return UpdateInitialDepositAmount()

    if obj["kind"] == "UpdateObligationOrdersEnabled":
        return UpdateObligationOrdersEnabled()

    kind = obj["kind"]
    raise ValueError(f"Unrecognized enum kind: {kind}")


layout = EnumForCodegen(
"UpdateOwner" / borsh.CStruct(),
"UpdateEmergencyMode" / borsh.CStruct(),
"UpdateLiquidationCloseFactor" / borsh.CStruct(),
"UpdateLiquidationMaxValue" / borsh.CStruct(),
"DeprecatedUpdateGlobalUnhealthyBorrow" / borsh.CStruct(),
"UpdateGlobalAllowedBorrow" / borsh.CStruct(),
"UpdateRiskCouncil" / borsh.CStruct(),
"UpdateMinFullLiquidationThreshold" / borsh.CStruct(),
"UpdateInsolvencyRiskLtv" / borsh.CStruct(),
"UpdateElevationGroup" / borsh.CStruct(),
"UpdateReferralFeeBps" / borsh.CStruct(),
"DeprecatedUpdateMultiplierPoints" / borsh.CStruct(),
"UpdatePriceRefreshTriggerToMaxAgePct" / borsh.CStruct(),
"UpdateAutodeleverageEnabled" / borsh.CStruct(),
"UpdateBorrowingDisabled" / borsh.CStruct(),
"UpdateMinNetValueObligationPostAction" / borsh.CStruct(),
"UpdateMinValueLtvSkipPriorityLiqCheck" / borsh.CStruct(),
"UpdateMinValueBfSkipPriorityLiqCheck" / borsh.CStruct(),
"UpdatePaddingFields" / borsh.CStruct(),
"UpdateName" / borsh.CStruct(),
"UpdateIndividualAutodeleverageMarginCallPeriodSecs" / borsh.CStruct(),
"UpdateInitialDepositAmount" / borsh.CStruct(),
"UpdateObligationOrdersEnabled" / borsh.CStruct(),
)
