'''
    This code was AUTOGENERATED using the codama library.
    Please DO NOT EDIT THIS FILE, instead use visitors
    to add features, then rerun codama to update it.
    @see https://github.com/codama-idl/codama
'''

import borsh_construct as borsh
import typing
from anchorpy.borsh_extension import EnumForCodegen
from dataclasses import dataclass


class UpdateLoanToValuePctJSON(typing.TypedDict):
    kind: typing.Literal["UpdateLoanToValuePct"]


@dataclass
class UpdateLoanToValuePct:
    discriminator: typing.ClassVar = 0
    def to_json(self) -> UpdateLoanToValuePctJSON:
        return UpdateLoanToValuePctJSON(
            kind="UpdateLoanToValuePct",
        )

    def to_encodable(self) -> dict[str, typing.Any]:
        return {
            "UpdateLoanToValuePct": {},
        }




class UpdateMaxLiquidationBonusBpsJSON(typing.TypedDict):
    kind: typing.Literal["UpdateMaxLiquidationBonusBps"]


@dataclass
class UpdateMaxLiquidationBonusBps:
    discriminator: typing.ClassVar = 1
    def to_json(self) -> UpdateMaxLiquidationBonusBpsJSON:
        return UpdateMaxLiquidationBonusBpsJSON(
            kind="UpdateMaxLiquidationBonusBps",
        )

    def to_encodable(self) -> dict[str, typing.Any]:
        return {
            "UpdateMaxLiquidationBonusBps": {},
        }




class UpdateLiquidationThresholdPctJSON(typing.TypedDict):
    kind: typing.Literal["UpdateLiquidationThresholdPct"]


@dataclass
class UpdateLiquidationThresholdPct:
    discriminator: typing.ClassVar = 2
    def to_json(self) -> UpdateLiquidationThresholdPctJSON:
        return UpdateLiquidationThresholdPctJSON(
            kind="UpdateLiquidationThresholdPct",
        )

    def to_encodable(self) -> dict[str, typing.Any]:
        return {
            "UpdateLiquidationThresholdPct": {},
        }




class UpdateProtocolLiquidationFeeJSON(typing.TypedDict):
    kind: typing.Literal["UpdateProtocolLiquidationFee"]


@dataclass
class UpdateProtocolLiquidationFee:
    discriminator: typing.ClassVar = 3
    def to_json(self) -> UpdateProtocolLiquidationFeeJSON:
        return UpdateProtocolLiquidationFeeJSON(
            kind="UpdateProtocolLiquidationFee",
        )

    def to_encodable(self) -> dict[str, typing.Any]:
        return {
            "UpdateProtocolLiquidationFee": {},
        }




class UpdateProtocolTakeRateJSON(typing.TypedDict):
    kind: typing.Literal["UpdateProtocolTakeRate"]


@dataclass
class UpdateProtocolTakeRate:
    discriminator: typing.ClassVar = 4
    def to_json(self) -> UpdateProtocolTakeRateJSON:
        return UpdateProtocolTakeRateJSON(
            kind="UpdateProtocolTakeRate",
        )

    def to_encodable(self) -> dict[str, typing.Any]:
        return {
            "UpdateProtocolTakeRate": {},
        }




class UpdateFeesBorrowFeeJSON(typing.TypedDict):
    kind: typing.Literal["UpdateFeesBorrowFee"]


@dataclass
class UpdateFeesBorrowFee:
    discriminator: typing.ClassVar = 5
    def to_json(self) -> UpdateFeesBorrowFeeJSON:
        return UpdateFeesBorrowFeeJSON(
            kind="UpdateFeesBorrowFee",
        )

    def to_encodable(self) -> dict[str, typing.Any]:
        return {
            "UpdateFeesBorrowFee": {},
        }




class UpdateFeesFlashLoanFeeJSON(typing.TypedDict):
    kind: typing.Literal["UpdateFeesFlashLoanFee"]


@dataclass
class UpdateFeesFlashLoanFee:
    discriminator: typing.ClassVar = 6
    def to_json(self) -> UpdateFeesFlashLoanFeeJSON:
        return UpdateFeesFlashLoanFeeJSON(
            kind="UpdateFeesFlashLoanFee",
        )

    def to_encodable(self) -> dict[str, typing.Any]:
        return {
            "UpdateFeesFlashLoanFee": {},
        }




class DeprecatedUpdateFeesReferralFeeBpsJSON(typing.TypedDict):
    kind: typing.Literal["DeprecatedUpdateFeesReferralFeeBps"]


@dataclass
class DeprecatedUpdateFeesReferralFeeBps:
    discriminator: typing.ClassVar = 7
    def to_json(self) -> DeprecatedUpdateFeesReferralFeeBpsJSON:
        return DeprecatedUpdateFeesReferralFeeBpsJSON(
            kind="DeprecatedUpdateFeesReferralFeeBps",
        )

    def to_encodable(self) -> dict[str, typing.Any]:
        return {
            "DeprecatedUpdateFeesReferralFeeBps": {},
        }




class UpdateDepositLimitJSON(typing.TypedDict):
    kind: typing.Literal["UpdateDepositLimit"]


@dataclass
class UpdateDepositLimit:
    discriminator: typing.ClassVar = 8
    def to_json(self) -> UpdateDepositLimitJSON:
        return UpdateDepositLimitJSON(
            kind="UpdateDepositLimit",
        )

    def to_encodable(self) -> dict[str, typing.Any]:
        return {
            "UpdateDepositLimit": {},
        }




class UpdateBorrowLimitJSON(typing.TypedDict):
    kind: typing.Literal["UpdateBorrowLimit"]


@dataclass
class UpdateBorrowLimit:
    discriminator: typing.ClassVar = 9
    def to_json(self) -> UpdateBorrowLimitJSON:
        return UpdateBorrowLimitJSON(
            kind="UpdateBorrowLimit",
        )

    def to_encodable(self) -> dict[str, typing.Any]:
        return {
            "UpdateBorrowLimit": {},
        }




class UpdateTokenInfoLowerHeuristicJSON(typing.TypedDict):
    kind: typing.Literal["UpdateTokenInfoLowerHeuristic"]


@dataclass
class UpdateTokenInfoLowerHeuristic:
    discriminator: typing.ClassVar = 10
    def to_json(self) -> UpdateTokenInfoLowerHeuristicJSON:
        return UpdateTokenInfoLowerHeuristicJSON(
            kind="UpdateTokenInfoLowerHeuristic",
        )

    def to_encodable(self) -> dict[str, typing.Any]:
        return {
            "UpdateTokenInfoLowerHeuristic": {},
        }




class UpdateTokenInfoUpperHeuristicJSON(typing.TypedDict):
    kind: typing.Literal["UpdateTokenInfoUpperHeuristic"]


@dataclass
class UpdateTokenInfoUpperHeuristic:
    discriminator: typing.ClassVar = 11
    def to_json(self) -> UpdateTokenInfoUpperHeuristicJSON:
        return UpdateTokenInfoUpperHeuristicJSON(
            kind="UpdateTokenInfoUpperHeuristic",
        )

    def to_encodable(self) -> dict[str, typing.Any]:
        return {
            "UpdateTokenInfoUpperHeuristic": {},
        }




class UpdateTokenInfoExpHeuristicJSON(typing.TypedDict):
    kind: typing.Literal["UpdateTokenInfoExpHeuristic"]


@dataclass
class UpdateTokenInfoExpHeuristic:
    discriminator: typing.ClassVar = 12
    def to_json(self) -> UpdateTokenInfoExpHeuristicJSON:
        return UpdateTokenInfoExpHeuristicJSON(
            kind="UpdateTokenInfoExpHeuristic",
        )

    def to_encodable(self) -> dict[str, typing.Any]:
        return {
            "UpdateTokenInfoExpHeuristic": {},
        }




class UpdateTokenInfoTwapDivergenceJSON(typing.TypedDict):
    kind: typing.Literal["UpdateTokenInfoTwapDivergence"]


@dataclass
class UpdateTokenInfoTwapDivergence:
    discriminator: typing.ClassVar = 13
    def to_json(self) -> UpdateTokenInfoTwapDivergenceJSON:
        return UpdateTokenInfoTwapDivergenceJSON(
            kind="UpdateTokenInfoTwapDivergence",
        )

    def to_encodable(self) -> dict[str, typing.Any]:
        return {
            "UpdateTokenInfoTwapDivergence": {},
        }




class UpdateTokenInfoScopeTwapJSON(typing.TypedDict):
    kind: typing.Literal["UpdateTokenInfoScopeTwap"]


@dataclass
class UpdateTokenInfoScopeTwap:
    discriminator: typing.ClassVar = 14
    def to_json(self) -> UpdateTokenInfoScopeTwapJSON:
        return UpdateTokenInfoScopeTwapJSON(
            kind="UpdateTokenInfoScopeTwap",
        )

    def to_encodable(self) -> dict[str, typing.Any]:
        return {
            "UpdateTokenInfoScopeTwap": {},
        }




class UpdateTokenInfoScopeChainJSON(typing.TypedDict):
    kind: typing.Literal["UpdateTokenInfoScopeChain"]


@dataclass
class UpdateTokenInfoScopeChain:
    discriminator: typing.ClassVar = 15
    def to_json(self) -> UpdateTokenInfoScopeChainJSON:
        return UpdateTokenInfoScopeChainJSON(
            kind="UpdateTokenInfoScopeChain",
        )

    def to_encodable(self) -> dict[str, typing.Any]:
        return {
            "UpdateTokenInfoScopeChain": {},
        }




class UpdateTokenInfoNameJSON(typing.TypedDict):
    kind: typing.Literal["UpdateTokenInfoName"]


@dataclass
class UpdateTokenInfoName:
    discriminator: typing.ClassVar = 16
    def to_json(self) -> UpdateTokenInfoNameJSON:
        return UpdateTokenInfoNameJSON(
            kind="UpdateTokenInfoName",
        )

    def to_encodable(self) -> dict[str, typing.Any]:
        return {
            "UpdateTokenInfoName": {},
        }




class UpdateTokenInfoPriceMaxAgeJSON(typing.TypedDict):
    kind: typing.Literal["UpdateTokenInfoPriceMaxAge"]


@dataclass
class UpdateTokenInfoPriceMaxAge:
    discriminator: typing.ClassVar = 17
    def to_json(self) -> UpdateTokenInfoPriceMaxAgeJSON:
        return UpdateTokenInfoPriceMaxAgeJSON(
            kind="UpdateTokenInfoPriceMaxAge",
        )

    def to_encodable(self) -> dict[str, typing.Any]:
        return {
            "UpdateTokenInfoPriceMaxAge": {},
        }




class UpdateTokenInfoTwapMaxAgeJSON(typing.TypedDict):
    kind: typing.Literal["UpdateTokenInfoTwapMaxAge"]


@dataclass
class UpdateTokenInfoTwapMaxAge:
    discriminator: typing.ClassVar = 18
    def to_json(self) -> UpdateTokenInfoTwapMaxAgeJSON:
        return UpdateTokenInfoTwapMaxAgeJSON(
            kind="UpdateTokenInfoTwapMaxAge",
        )

    def to_encodable(self) -> dict[str, typing.Any]:
        return {
            "UpdateTokenInfoTwapMaxAge": {},
        }




class UpdateScopePriceFeedJSON(typing.TypedDict):
    kind: typing.Literal["UpdateScopePriceFeed"]


@dataclass
class UpdateScopePriceFeed:
    discriminator: typing.ClassVar = 19
    def to_json(self) -> UpdateScopePriceFeedJSON:
        return UpdateScopePriceFeedJSON(
            kind="UpdateScopePriceFeed",
        )

    def to_encodable(self) -> dict[str, typing.Any]:
        return {
            "UpdateScopePriceFeed": {},
        }




class UpdatePythPriceJSON(typing.TypedDict):
    kind: typing.Literal["UpdatePythPrice"]


@dataclass
class UpdatePythPrice:
    discriminator: typing.ClassVar = 20
    def to_json(self) -> UpdatePythPriceJSON:
        return UpdatePythPriceJSON(
            kind="UpdatePythPrice",
        )

    def to_encodable(self) -> dict[str, typing.Any]:
        return {
            "UpdatePythPrice": {},
        }




class UpdateSwitchboardFeedJSON(typing.TypedDict):
    kind: typing.Literal["UpdateSwitchboardFeed"]


@dataclass
class UpdateSwitchboardFeed:
    discriminator: typing.ClassVar = 21
    def to_json(self) -> UpdateSwitchboardFeedJSON:
        return UpdateSwitchboardFeedJSON(
            kind="UpdateSwitchboardFeed",
        )

    def to_encodable(self) -> dict[str, typing.Any]:
        return {
            "UpdateSwitchboardFeed": {},
        }




class UpdateSwitchboardTwapFeedJSON(typing.TypedDict):
    kind: typing.Literal["UpdateSwitchboardTwapFeed"]


@dataclass
class UpdateSwitchboardTwapFeed:
    discriminator: typing.ClassVar = 22
    def to_json(self) -> UpdateSwitchboardTwapFeedJSON:
        return UpdateSwitchboardTwapFeedJSON(
            kind="UpdateSwitchboardTwapFeed",
        )

    def to_encodable(self) -> dict[str, typing.Any]:
        return {
            "UpdateSwitchboardTwapFeed": {},
        }




class UpdateBorrowRateCurveJSON(typing.TypedDict):
    kind: typing.Literal["UpdateBorrowRateCurve"]


@dataclass
class UpdateBorrowRateCurve:
    discriminator: typing.ClassVar = 23
    def to_json(self) -> UpdateBorrowRateCurveJSON:
        return UpdateBorrowRateCurveJSON(
            kind="UpdateBorrowRateCurve",
        )

    def to_encodable(self) -> dict[str, typing.Any]:
        return {
            "UpdateBorrowRateCurve": {},
        }




class UpdateEntireReserveConfigJSON(typing.TypedDict):
    kind: typing.Literal["UpdateEntireReserveConfig"]


@dataclass
class UpdateEntireReserveConfig:
    discriminator: typing.ClassVar = 24
    def to_json(self) -> UpdateEntireReserveConfigJSON:
        return UpdateEntireReserveConfigJSON(
            kind="UpdateEntireReserveConfig",
        )

    def to_encodable(self) -> dict[str, typing.Any]:
        return {
            "UpdateEntireReserveConfig": {},
        }




class UpdateDebtWithdrawalCapJSON(typing.TypedDict):
    kind: typing.Literal["UpdateDebtWithdrawalCap"]


@dataclass
class UpdateDebtWithdrawalCap:
    discriminator: typing.ClassVar = 25
    def to_json(self) -> UpdateDebtWithdrawalCapJSON:
        return UpdateDebtWithdrawalCapJSON(
            kind="UpdateDebtWithdrawalCap",
        )

    def to_encodable(self) -> dict[str, typing.Any]:
        return {
            "UpdateDebtWithdrawalCap": {},
        }




class UpdateDepositWithdrawalCapJSON(typing.TypedDict):
    kind: typing.Literal["UpdateDepositWithdrawalCap"]


@dataclass
class UpdateDepositWithdrawalCap:
    discriminator: typing.ClassVar = 26
    def to_json(self) -> UpdateDepositWithdrawalCapJSON:
        return UpdateDepositWithdrawalCapJSON(
            kind="UpdateDepositWithdrawalCap",
        )

    def to_encodable(self) -> dict[str, typing.Any]:
        return {
            "UpdateDepositWithdrawalCap": {},
        }




class DeprecatedUpdateDebtWithdrawalCapCurrentTotalJSON(typing.TypedDict):
    kind: typing.Literal["DeprecatedUpdateDebtWithdrawalCapCurrentTotal"]


@dataclass
class DeprecatedUpdateDebtWithdrawalCapCurrentTotal:
    discriminator: typing.ClassVar = 27
    def to_json(self) -> DeprecatedUpdateDebtWithdrawalCapCurrentTotalJSON:
        return DeprecatedUpdateDebtWithdrawalCapCurrentTotalJSON(
            kind="DeprecatedUpdateDebtWithdrawalCapCurrentTotal",
        )

    def to_encodable(self) -> dict[str, typing.Any]:
        return {
            "DeprecatedUpdateDebtWithdrawalCapCurrentTotal": {},
        }




class DeprecatedUpdateDepositWithdrawalCapCurrentTotalJSON(typing.TypedDict):
    kind: typing.Literal["DeprecatedUpdateDepositWithdrawalCapCurrentTotal"]


@dataclass
class DeprecatedUpdateDepositWithdrawalCapCurrentTotal:
    discriminator: typing.ClassVar = 28
    def to_json(self) -> DeprecatedUpdateDepositWithdrawalCapCurrentTotalJSON:
        return DeprecatedUpdateDepositWithdrawalCapCurrentTotalJSON(
            kind="DeprecatedUpdateDepositWithdrawalCapCurrentTotal",
        )

    def to_encodable(self) -> dict[str, typing.Any]:
        return {
            "DeprecatedUpdateDepositWithdrawalCapCurrentTotal": {},
        }




class UpdateBadDebtLiquidationBonusBpsJSON(typing.TypedDict):
    kind: typing.Literal["UpdateBadDebtLiquidationBonusBps"]


@dataclass
class UpdateBadDebtLiquidationBonusBps:
    discriminator: typing.ClassVar = 29
    def to_json(self) -> UpdateBadDebtLiquidationBonusBpsJSON:
        return UpdateBadDebtLiquidationBonusBpsJSON(
            kind="UpdateBadDebtLiquidationBonusBps",
        )

    def to_encodable(self) -> dict[str, typing.Any]:
        return {
            "UpdateBadDebtLiquidationBonusBps": {},
        }




class UpdateMinLiquidationBonusBpsJSON(typing.TypedDict):
    kind: typing.Literal["UpdateMinLiquidationBonusBps"]


@dataclass
class UpdateMinLiquidationBonusBps:
    discriminator: typing.ClassVar = 30
    def to_json(self) -> UpdateMinLiquidationBonusBpsJSON:
        return UpdateMinLiquidationBonusBpsJSON(
            kind="UpdateMinLiquidationBonusBps",
        )

    def to_encodable(self) -> dict[str, typing.Any]:
        return {
            "UpdateMinLiquidationBonusBps": {},
        }




class UpdateDeleveragingMarginCallPeriodJSON(typing.TypedDict):
    kind: typing.Literal["UpdateDeleveragingMarginCallPeriod"]


@dataclass
class UpdateDeleveragingMarginCallPeriod:
    discriminator: typing.ClassVar = 31
    def to_json(self) -> UpdateDeleveragingMarginCallPeriodJSON:
        return UpdateDeleveragingMarginCallPeriodJSON(
            kind="UpdateDeleveragingMarginCallPeriod",
        )

    def to_encodable(self) -> dict[str, typing.Any]:
        return {
            "UpdateDeleveragingMarginCallPeriod": {},
        }




class UpdateBorrowFactorJSON(typing.TypedDict):
    kind: typing.Literal["UpdateBorrowFactor"]


@dataclass
class UpdateBorrowFactor:
    discriminator: typing.ClassVar = 32
    def to_json(self) -> UpdateBorrowFactorJSON:
        return UpdateBorrowFactorJSON(
            kind="UpdateBorrowFactor",
        )

    def to_encodable(self) -> dict[str, typing.Any]:
        return {
            "UpdateBorrowFactor": {},
        }




class UpdateAssetTierJSON(typing.TypedDict):
    kind: typing.Literal["UpdateAssetTier"]


@dataclass
class UpdateAssetTier:
    discriminator: typing.ClassVar = 33
    def to_json(self) -> UpdateAssetTierJSON:
        return UpdateAssetTierJSON(
            kind="UpdateAssetTier",
        )

    def to_encodable(self) -> dict[str, typing.Any]:
        return {
            "UpdateAssetTier": {},
        }




class UpdateElevationGroupJSON(typing.TypedDict):
    kind: typing.Literal["UpdateElevationGroup"]


@dataclass
class UpdateElevationGroup:
    discriminator: typing.ClassVar = 34
    def to_json(self) -> UpdateElevationGroupJSON:
        return UpdateElevationGroupJSON(
            kind="UpdateElevationGroup",
        )

    def to_encodable(self) -> dict[str, typing.Any]:
        return {
            "UpdateElevationGroup": {},
        }




class UpdateDeleveragingThresholdDecreaseBpsPerDayJSON(typing.TypedDict):
    kind: typing.Literal["UpdateDeleveragingThresholdDecreaseBpsPerDay"]


@dataclass
class UpdateDeleveragingThresholdDecreaseBpsPerDay:
    discriminator: typing.ClassVar = 35
    def to_json(self) -> UpdateDeleveragingThresholdDecreaseBpsPerDayJSON:
        return UpdateDeleveragingThresholdDecreaseBpsPerDayJSON(
            kind="UpdateDeleveragingThresholdDecreaseBpsPerDay",
        )

    def to_encodable(self) -> dict[str, typing.Any]:
        return {
            "UpdateDeleveragingThresholdDecreaseBpsPerDay": {},
        }




class DeprecatedUpdateMultiplierSideBoostJSON(typing.TypedDict):
    kind: typing.Literal["DeprecatedUpdateMultiplierSideBoost"]


@dataclass
class DeprecatedUpdateMultiplierSideBoost:
    discriminator: typing.ClassVar = 36
    def to_json(self) -> DeprecatedUpdateMultiplierSideBoostJSON:
        return DeprecatedUpdateMultiplierSideBoostJSON(
            kind="DeprecatedUpdateMultiplierSideBoost",
        )

    def to_encodable(self) -> dict[str, typing.Any]:
        return {
            "DeprecatedUpdateMultiplierSideBoost": {},
        }




class DeprecatedUpdateMultiplierTagBoostJSON(typing.TypedDict):
    kind: typing.Literal["DeprecatedUpdateMultiplierTagBoost"]


@dataclass
class DeprecatedUpdateMultiplierTagBoost:
    discriminator: typing.ClassVar = 37
    def to_json(self) -> DeprecatedUpdateMultiplierTagBoostJSON:
        return DeprecatedUpdateMultiplierTagBoostJSON(
            kind="DeprecatedUpdateMultiplierTagBoost",
        )

    def to_encodable(self) -> dict[str, typing.Any]:
        return {
            "DeprecatedUpdateMultiplierTagBoost": {},
        }




class UpdateReserveStatusJSON(typing.TypedDict):
    kind: typing.Literal["UpdateReserveStatus"]


@dataclass
class UpdateReserveStatus:
    discriminator: typing.ClassVar = 38
    def to_json(self) -> UpdateReserveStatusJSON:
        return UpdateReserveStatusJSON(
            kind="UpdateReserveStatus",
        )

    def to_encodable(self) -> dict[str, typing.Any]:
        return {
            "UpdateReserveStatus": {},
        }




class UpdateFarmCollateralJSON(typing.TypedDict):
    kind: typing.Literal["UpdateFarmCollateral"]


@dataclass
class UpdateFarmCollateral:
    discriminator: typing.ClassVar = 39
    def to_json(self) -> UpdateFarmCollateralJSON:
        return UpdateFarmCollateralJSON(
            kind="UpdateFarmCollateral",
        )

    def to_encodable(self) -> dict[str, typing.Any]:
        return {
            "UpdateFarmCollateral": {},
        }




class UpdateFarmDebtJSON(typing.TypedDict):
    kind: typing.Literal["UpdateFarmDebt"]


@dataclass
class UpdateFarmDebt:
    discriminator: typing.ClassVar = 40
    def to_json(self) -> UpdateFarmDebtJSON:
        return UpdateFarmDebtJSON(
            kind="UpdateFarmDebt",
        )

    def to_encodable(self) -> dict[str, typing.Any]:
        return {
            "UpdateFarmDebt": {},
        }




class UpdateDisableUsageAsCollateralOutsideEmodeJSON(typing.TypedDict):
    kind: typing.Literal["UpdateDisableUsageAsCollateralOutsideEmode"]


@dataclass
class UpdateDisableUsageAsCollateralOutsideEmode:
    discriminator: typing.ClassVar = 41
    def to_json(self) -> UpdateDisableUsageAsCollateralOutsideEmodeJSON:
        return UpdateDisableUsageAsCollateralOutsideEmodeJSON(
            kind="UpdateDisableUsageAsCollateralOutsideEmode",
        )

    def to_encodable(self) -> dict[str, typing.Any]:
        return {
            "UpdateDisableUsageAsCollateralOutsideEmode": {},
        }




class UpdateBlockBorrowingAboveUtilizationPctJSON(typing.TypedDict):
    kind: typing.Literal["UpdateBlockBorrowingAboveUtilizationPct"]


@dataclass
class UpdateBlockBorrowingAboveUtilizationPct:
    discriminator: typing.ClassVar = 42
    def to_json(self) -> UpdateBlockBorrowingAboveUtilizationPctJSON:
        return UpdateBlockBorrowingAboveUtilizationPctJSON(
            kind="UpdateBlockBorrowingAboveUtilizationPct",
        )

    def to_encodable(self) -> dict[str, typing.Any]:
        return {
            "UpdateBlockBorrowingAboveUtilizationPct": {},
        }




class UpdateBlockPriceUsageJSON(typing.TypedDict):
    kind: typing.Literal["UpdateBlockPriceUsage"]


@dataclass
class UpdateBlockPriceUsage:
    discriminator: typing.ClassVar = 43
    def to_json(self) -> UpdateBlockPriceUsageJSON:
        return UpdateBlockPriceUsageJSON(
            kind="UpdateBlockPriceUsage",
        )

    def to_encodable(self) -> dict[str, typing.Any]:
        return {
            "UpdateBlockPriceUsage": {},
        }




class UpdateBorrowLimitOutsideElevationGroupJSON(typing.TypedDict):
    kind: typing.Literal["UpdateBorrowLimitOutsideElevationGroup"]


@dataclass
class UpdateBorrowLimitOutsideElevationGroup:
    discriminator: typing.ClassVar = 44
    def to_json(self) -> UpdateBorrowLimitOutsideElevationGroupJSON:
        return UpdateBorrowLimitOutsideElevationGroupJSON(
            kind="UpdateBorrowLimitOutsideElevationGroup",
        )

    def to_encodable(self) -> dict[str, typing.Any]:
        return {
            "UpdateBorrowLimitOutsideElevationGroup": {},
        }




class UpdateBorrowLimitsInElevationGroupAgainstThisReserveJSON(typing.TypedDict):
    kind: typing.Literal["UpdateBorrowLimitsInElevationGroupAgainstThisReserve"]


@dataclass
class UpdateBorrowLimitsInElevationGroupAgainstThisReserve:
    discriminator: typing.ClassVar = 45
    def to_json(self) -> UpdateBorrowLimitsInElevationGroupAgainstThisReserveJSON:
        return UpdateBorrowLimitsInElevationGroupAgainstThisReserveJSON(
            kind="UpdateBorrowLimitsInElevationGroupAgainstThisReserve",
        )

    def to_encodable(self) -> dict[str, typing.Any]:
        return {
            "UpdateBorrowLimitsInElevationGroupAgainstThisReserve": {},
        }




class UpdateHostFixedInterestRateBpsJSON(typing.TypedDict):
    kind: typing.Literal["UpdateHostFixedInterestRateBps"]


@dataclass
class UpdateHostFixedInterestRateBps:
    discriminator: typing.ClassVar = 46
    def to_json(self) -> UpdateHostFixedInterestRateBpsJSON:
        return UpdateHostFixedInterestRateBpsJSON(
            kind="UpdateHostFixedInterestRateBps",
        )

    def to_encodable(self) -> dict[str, typing.Any]:
        return {
            "UpdateHostFixedInterestRateBps": {},
        }




class UpdateAutodeleverageEnabledJSON(typing.TypedDict):
    kind: typing.Literal["UpdateAutodeleverageEnabled"]


@dataclass
class UpdateAutodeleverageEnabled:
    discriminator: typing.ClassVar = 47
    def to_json(self) -> UpdateAutodeleverageEnabledJSON:
        return UpdateAutodeleverageEnabledJSON(
            kind="UpdateAutodeleverageEnabled",
        )

    def to_encodable(self) -> dict[str, typing.Any]:
        return {
            "UpdateAutodeleverageEnabled": {},
        }




class UpdateDeleveragingBonusIncreaseBpsPerDayJSON(typing.TypedDict):
    kind: typing.Literal["UpdateDeleveragingBonusIncreaseBpsPerDay"]


@dataclass
class UpdateDeleveragingBonusIncreaseBpsPerDay:
    discriminator: typing.ClassVar = 48
    def to_json(self) -> UpdateDeleveragingBonusIncreaseBpsPerDayJSON:
        return UpdateDeleveragingBonusIncreaseBpsPerDayJSON(
            kind="UpdateDeleveragingBonusIncreaseBpsPerDay",
        )

    def to_encodable(self) -> dict[str, typing.Any]:
        return {
            "UpdateDeleveragingBonusIncreaseBpsPerDay": {},
        }




class UpdateProtocolOrderExecutionFeeJSON(typing.TypedDict):
    kind: typing.Literal["UpdateProtocolOrderExecutionFee"]


@dataclass
class UpdateProtocolOrderExecutionFee:
    discriminator: typing.ClassVar = 49
    def to_json(self) -> UpdateProtocolOrderExecutionFeeJSON:
        return UpdateProtocolOrderExecutionFeeJSON(
            kind="UpdateProtocolOrderExecutionFee",
        )

    def to_encodable(self) -> dict[str, typing.Any]:
        return {
            "UpdateProtocolOrderExecutionFee": {},
        }





UpdateConfigModeKind = typing.Union[
    UpdateLoanToValuePct,
    UpdateMaxLiquidationBonusBps,
    UpdateLiquidationThresholdPct,
    UpdateProtocolLiquidationFee,
    UpdateProtocolTakeRate,
    UpdateFeesBorrowFee,
    UpdateFeesFlashLoanFee,
    DeprecatedUpdateFeesReferralFeeBps,
    UpdateDepositLimit,
    UpdateBorrowLimit,
    UpdateTokenInfoLowerHeuristic,
    UpdateTokenInfoUpperHeuristic,
    UpdateTokenInfoExpHeuristic,
    UpdateTokenInfoTwapDivergence,
    UpdateTokenInfoScopeTwap,
    UpdateTokenInfoScopeChain,
    UpdateTokenInfoName,
    UpdateTokenInfoPriceMaxAge,
    UpdateTokenInfoTwapMaxAge,
    UpdateScopePriceFeed,
    UpdatePythPrice,
    UpdateSwitchboardFeed,
    UpdateSwitchboardTwapFeed,
    UpdateBorrowRateCurve,
    UpdateEntireReserveConfig,
    UpdateDebtWithdrawalCap,
    UpdateDepositWithdrawalCap,
    DeprecatedUpdateDebtWithdrawalCapCurrentTotal,
    DeprecatedUpdateDepositWithdrawalCapCurrentTotal,
    UpdateBadDebtLiquidationBonusBps,
    UpdateMinLiquidationBonusBps,
    UpdateDeleveragingMarginCallPeriod,
    UpdateBorrowFactor,
    UpdateAssetTier,
    UpdateElevationGroup,
    UpdateDeleveragingThresholdDecreaseBpsPerDay,
    DeprecatedUpdateMultiplierSideBoost,
    DeprecatedUpdateMultiplierTagBoost,
    UpdateReserveStatus,
    UpdateFarmCollateral,
    UpdateFarmDebt,
    UpdateDisableUsageAsCollateralOutsideEmode,
    UpdateBlockBorrowingAboveUtilizationPct,
    UpdateBlockPriceUsage,
    UpdateBorrowLimitOutsideElevationGroup,
    UpdateBorrowLimitsInElevationGroupAgainstThisReserve,
    UpdateHostFixedInterestRateBps,
    UpdateAutodeleverageEnabled,
    UpdateDeleveragingBonusIncreaseBpsPerDay,
    UpdateProtocolOrderExecutionFee,
]
UpdateConfigModeJSON = typing.Union[
    UpdateLoanToValuePctJSON,
    UpdateMaxLiquidationBonusBpsJSON,
    UpdateLiquidationThresholdPctJSON,
    UpdateProtocolLiquidationFeeJSON,
    UpdateProtocolTakeRateJSON,
    UpdateFeesBorrowFeeJSON,
    UpdateFeesFlashLoanFeeJSON,
    DeprecatedUpdateFeesReferralFeeBpsJSON,
    UpdateDepositLimitJSON,
    UpdateBorrowLimitJSON,
    UpdateTokenInfoLowerHeuristicJSON,
    UpdateTokenInfoUpperHeuristicJSON,
    UpdateTokenInfoExpHeuristicJSON,
    UpdateTokenInfoTwapDivergenceJSON,
    UpdateTokenInfoScopeTwapJSON,
    UpdateTokenInfoScopeChainJSON,
    UpdateTokenInfoNameJSON,
    UpdateTokenInfoPriceMaxAgeJSON,
    UpdateTokenInfoTwapMaxAgeJSON,
    UpdateScopePriceFeedJSON,
    UpdatePythPriceJSON,
    UpdateSwitchboardFeedJSON,
    UpdateSwitchboardTwapFeedJSON,
    UpdateBorrowRateCurveJSON,
    UpdateEntireReserveConfigJSON,
    UpdateDebtWithdrawalCapJSON,
    UpdateDepositWithdrawalCapJSON,
    DeprecatedUpdateDebtWithdrawalCapCurrentTotalJSON,
    DeprecatedUpdateDepositWithdrawalCapCurrentTotalJSON,
    UpdateBadDebtLiquidationBonusBpsJSON,
    UpdateMinLiquidationBonusBpsJSON,
    UpdateDeleveragingMarginCallPeriodJSON,
    UpdateBorrowFactorJSON,
    UpdateAssetTierJSON,
    UpdateElevationGroupJSON,
    UpdateDeleveragingThresholdDecreaseBpsPerDayJSON,
    DeprecatedUpdateMultiplierSideBoostJSON,
    DeprecatedUpdateMultiplierTagBoostJSON,
    UpdateReserveStatusJSON,
    UpdateFarmCollateralJSON,
    UpdateFarmDebtJSON,
    UpdateDisableUsageAsCollateralOutsideEmodeJSON,
    UpdateBlockBorrowingAboveUtilizationPctJSON,
    UpdateBlockPriceUsageJSON,
    UpdateBorrowLimitOutsideElevationGroupJSON,
    UpdateBorrowLimitsInElevationGroupAgainstThisReserveJSON,
    UpdateHostFixedInterestRateBpsJSON,
    UpdateAutodeleverageEnabledJSON,
    UpdateDeleveragingBonusIncreaseBpsPerDayJSON,
    UpdateProtocolOrderExecutionFeeJSON,
]

def from_decoded(obj: dict) -> UpdateConfigModeKind:
    if not isinstance(obj, dict):
        raise ValueError("Invalid enum object")
    if "UpdateLoanToValuePct" in obj:
      return UpdateLoanToValuePct()
    if "UpdateMaxLiquidationBonusBps" in obj:
      return UpdateMaxLiquidationBonusBps()
    if "UpdateLiquidationThresholdPct" in obj:
      return UpdateLiquidationThresholdPct()
    if "UpdateProtocolLiquidationFee" in obj:
      return UpdateProtocolLiquidationFee()
    if "UpdateProtocolTakeRate" in obj:
      return UpdateProtocolTakeRate()
    if "UpdateFeesBorrowFee" in obj:
      return UpdateFeesBorrowFee()
    if "UpdateFeesFlashLoanFee" in obj:
      return UpdateFeesFlashLoanFee()
    if "DeprecatedUpdateFeesReferralFeeBps" in obj:
      return DeprecatedUpdateFeesReferralFeeBps()
    if "UpdateDepositLimit" in obj:
      return UpdateDepositLimit()
    if "UpdateBorrowLimit" in obj:
      return UpdateBorrowLimit()
    if "UpdateTokenInfoLowerHeuristic" in obj:
      return UpdateTokenInfoLowerHeuristic()
    if "UpdateTokenInfoUpperHeuristic" in obj:
      return UpdateTokenInfoUpperHeuristic()
    if "UpdateTokenInfoExpHeuristic" in obj:
      return UpdateTokenInfoExpHeuristic()
    if "UpdateTokenInfoTwapDivergence" in obj:
      return UpdateTokenInfoTwapDivergence()
    if "UpdateTokenInfoScopeTwap" in obj:
      return UpdateTokenInfoScopeTwap()
    if "UpdateTokenInfoScopeChain" in obj:
      return UpdateTokenInfoScopeChain()
    if "UpdateTokenInfoName" in obj:
      return UpdateTokenInfoName()
    if "UpdateTokenInfoPriceMaxAge" in obj:
      return UpdateTokenInfoPriceMaxAge()
    if "UpdateTokenInfoTwapMaxAge" in obj:
      return UpdateTokenInfoTwapMaxAge()
    if "UpdateScopePriceFeed" in obj:
      return UpdateScopePriceFeed()
    if "UpdatePythPrice" in obj:
      return UpdatePythPrice()
    if "UpdateSwitchboardFeed" in obj:
      return UpdateSwitchboardFeed()
    if "UpdateSwitchboardTwapFeed" in obj:
      return UpdateSwitchboardTwapFeed()
    if "UpdateBorrowRateCurve" in obj:
      return UpdateBorrowRateCurve()
    if "UpdateEntireReserveConfig" in obj:
      return UpdateEntireReserveConfig()
    if "UpdateDebtWithdrawalCap" in obj:
      return UpdateDebtWithdrawalCap()
    if "UpdateDepositWithdrawalCap" in obj:
      return UpdateDepositWithdrawalCap()
    if "DeprecatedUpdateDebtWithdrawalCapCurrentTotal" in obj:
      return DeprecatedUpdateDebtWithdrawalCapCurrentTotal()
    if "DeprecatedUpdateDepositWithdrawalCapCurrentTotal" in obj:
      return DeprecatedUpdateDepositWithdrawalCapCurrentTotal()
    if "UpdateBadDebtLiquidationBonusBps" in obj:
      return UpdateBadDebtLiquidationBonusBps()
    if "UpdateMinLiquidationBonusBps" in obj:
      return UpdateMinLiquidationBonusBps()
    if "UpdateDeleveragingMarginCallPeriod" in obj:
      return UpdateDeleveragingMarginCallPeriod()
    if "UpdateBorrowFactor" in obj:
      return UpdateBorrowFactor()
    if "UpdateAssetTier" in obj:
      return UpdateAssetTier()
    if "UpdateElevationGroup" in obj:
      return UpdateElevationGroup()
    if "UpdateDeleveragingThresholdDecreaseBpsPerDay" in obj:
      return UpdateDeleveragingThresholdDecreaseBpsPerDay()
    if "DeprecatedUpdateMultiplierSideBoost" in obj:
      return DeprecatedUpdateMultiplierSideBoost()
    if "DeprecatedUpdateMultiplierTagBoost" in obj:
      return DeprecatedUpdateMultiplierTagBoost()
    if "UpdateReserveStatus" in obj:
      return UpdateReserveStatus()
    if "UpdateFarmCollateral" in obj:
      return UpdateFarmCollateral()
    if "UpdateFarmDebt" in obj:
      return UpdateFarmDebt()
    if "UpdateDisableUsageAsCollateralOutsideEmode" in obj:
      return UpdateDisableUsageAsCollateralOutsideEmode()
    if "UpdateBlockBorrowingAboveUtilizationPct" in obj:
      return UpdateBlockBorrowingAboveUtilizationPct()
    if "UpdateBlockPriceUsage" in obj:
      return UpdateBlockPriceUsage()
    if "UpdateBorrowLimitOutsideElevationGroup" in obj:
      return UpdateBorrowLimitOutsideElevationGroup()
    if "UpdateBorrowLimitsInElevationGroupAgainstThisReserve" in obj:
      return UpdateBorrowLimitsInElevationGroupAgainstThisReserve()
    if "UpdateHostFixedInterestRateBps" in obj:
      return UpdateHostFixedInterestRateBps()
    if "UpdateAutodeleverageEnabled" in obj:
      return UpdateAutodeleverageEnabled()
    if "UpdateDeleveragingBonusIncreaseBpsPerDay" in obj:
      return UpdateDeleveragingBonusIncreaseBpsPerDay()
    if "UpdateProtocolOrderExecutionFee" in obj:
      return UpdateProtocolOrderExecutionFee()
    raise ValueError("Invalid enum object")

def from_json(obj: UpdateConfigModeJSON) -> UpdateConfigModeKind:
    if obj["kind"] == "UpdateLoanToValuePct":
        return UpdateLoanToValuePct()

    if obj["kind"] == "UpdateMaxLiquidationBonusBps":
        return UpdateMaxLiquidationBonusBps()

    if obj["kind"] == "UpdateLiquidationThresholdPct":
        return UpdateLiquidationThresholdPct()

    if obj["kind"] == "UpdateProtocolLiquidationFee":
        return UpdateProtocolLiquidationFee()

    if obj["kind"] == "UpdateProtocolTakeRate":
        return UpdateProtocolTakeRate()

    if obj["kind"] == "UpdateFeesBorrowFee":
        return UpdateFeesBorrowFee()

    if obj["kind"] == "UpdateFeesFlashLoanFee":
        return UpdateFeesFlashLoanFee()

    if obj["kind"] == "DeprecatedUpdateFeesReferralFeeBps":
        return DeprecatedUpdateFeesReferralFeeBps()

    if obj["kind"] == "UpdateDepositLimit":
        return UpdateDepositLimit()

    if obj["kind"] == "UpdateBorrowLimit":
        return UpdateBorrowLimit()

    if obj["kind"] == "UpdateTokenInfoLowerHeuristic":
        return UpdateTokenInfoLowerHeuristic()

    if obj["kind"] == "UpdateTokenInfoUpperHeuristic":
        return UpdateTokenInfoUpperHeuristic()

    if obj["kind"] == "UpdateTokenInfoExpHeuristic":
        return UpdateTokenInfoExpHeuristic()

    if obj["kind"] == "UpdateTokenInfoTwapDivergence":
        return UpdateTokenInfoTwapDivergence()

    if obj["kind"] == "UpdateTokenInfoScopeTwap":
        return UpdateTokenInfoScopeTwap()

    if obj["kind"] == "UpdateTokenInfoScopeChain":
        return UpdateTokenInfoScopeChain()

    if obj["kind"] == "UpdateTokenInfoName":
        return UpdateTokenInfoName()

    if obj["kind"] == "UpdateTokenInfoPriceMaxAge":
        return UpdateTokenInfoPriceMaxAge()

    if obj["kind"] == "UpdateTokenInfoTwapMaxAge":
        return UpdateTokenInfoTwapMaxAge()

    if obj["kind"] == "UpdateScopePriceFeed":
        return UpdateScopePriceFeed()

    if obj["kind"] == "UpdatePythPrice":
        return UpdatePythPrice()

    if obj["kind"] == "UpdateSwitchboardFeed":
        return UpdateSwitchboardFeed()

    if obj["kind"] == "UpdateSwitchboardTwapFeed":
        return UpdateSwitchboardTwapFeed()

    if obj["kind"] == "UpdateBorrowRateCurve":
        return UpdateBorrowRateCurve()

    if obj["kind"] == "UpdateEntireReserveConfig":
        return UpdateEntireReserveConfig()

    if obj["kind"] == "UpdateDebtWithdrawalCap":
        return UpdateDebtWithdrawalCap()

    if obj["kind"] == "UpdateDepositWithdrawalCap":
        return UpdateDepositWithdrawalCap()

    if obj["kind"] == "DeprecatedUpdateDebtWithdrawalCapCurrentTotal":
        return DeprecatedUpdateDebtWithdrawalCapCurrentTotal()

    if obj["kind"] == "DeprecatedUpdateDepositWithdrawalCapCurrentTotal":
        return DeprecatedUpdateDepositWithdrawalCapCurrentTotal()

    if obj["kind"] == "UpdateBadDebtLiquidationBonusBps":
        return UpdateBadDebtLiquidationBonusBps()

    if obj["kind"] == "UpdateMinLiquidationBonusBps":
        return UpdateMinLiquidationBonusBps()

    if obj["kind"] == "UpdateDeleveragingMarginCallPeriod":
        return UpdateDeleveragingMarginCallPeriod()

    if obj["kind"] == "UpdateBorrowFactor":
        return UpdateBorrowFactor()

    if obj["kind"] == "UpdateAssetTier":
        return UpdateAssetTier()

    if obj["kind"] == "UpdateElevationGroup":
        return UpdateElevationGroup()

    if obj["kind"] == "UpdateDeleveragingThresholdDecreaseBpsPerDay":
        return UpdateDeleveragingThresholdDecreaseBpsPerDay()

    if obj["kind"] == "DeprecatedUpdateMultiplierSideBoost":
        return DeprecatedUpdateMultiplierSideBoost()

    if obj["kind"] == "DeprecatedUpdateMultiplierTagBoost":
        return DeprecatedUpdateMultiplierTagBoost()

    if obj["kind"] == "UpdateReserveStatus":
        return UpdateReserveStatus()

    if obj["kind"] == "UpdateFarmCollateral":
        return UpdateFarmCollateral()

    if obj["kind"] == "UpdateFarmDebt":
        return UpdateFarmDebt()

    if obj["kind"] == "UpdateDisableUsageAsCollateralOutsideEmode":
        return UpdateDisableUsageAsCollateralOutsideEmode()

    if obj["kind"] == "UpdateBlockBorrowingAboveUtilizationPct":
        return UpdateBlockBorrowingAboveUtilizationPct()

    if obj["kind"] == "UpdateBlockPriceUsage":
        return UpdateBlockPriceUsage()

    if obj["kind"] == "UpdateBorrowLimitOutsideElevationGroup":
        return UpdateBorrowLimitOutsideElevationGroup()

    if obj["kind"] == "UpdateBorrowLimitsInElevationGroupAgainstThisReserve":
        return UpdateBorrowLimitsInElevationGroupAgainstThisReserve()

    if obj["kind"] == "UpdateHostFixedInterestRateBps":
        return UpdateHostFixedInterestRateBps()

    if obj["kind"] == "UpdateAutodeleverageEnabled":
        return UpdateAutodeleverageEnabled()

    if obj["kind"] == "UpdateDeleveragingBonusIncreaseBpsPerDay":
        return UpdateDeleveragingBonusIncreaseBpsPerDay()

    if obj["kind"] == "UpdateProtocolOrderExecutionFee":
        return UpdateProtocolOrderExecutionFee()

    kind = obj["kind"]
    raise ValueError(f"Unrecognized enum kind: {kind}")


layout = EnumForCodegen(
"UpdateLoanToValuePct" / borsh.CStruct(),
"UpdateMaxLiquidationBonusBps" / borsh.CStruct(),
"UpdateLiquidationThresholdPct" / borsh.CStruct(),
"UpdateProtocolLiquidationFee" / borsh.CStruct(),
"UpdateProtocolTakeRate" / borsh.CStruct(),
"UpdateFeesBorrowFee" / borsh.CStruct(),
"UpdateFeesFlashLoanFee" / borsh.CStruct(),
"DeprecatedUpdateFeesReferralFeeBps" / borsh.CStruct(),
"UpdateDepositLimit" / borsh.CStruct(),
"UpdateBorrowLimit" / borsh.CStruct(),
"UpdateTokenInfoLowerHeuristic" / borsh.CStruct(),
"UpdateTokenInfoUpperHeuristic" / borsh.CStruct(),
"UpdateTokenInfoExpHeuristic" / borsh.CStruct(),
"UpdateTokenInfoTwapDivergence" / borsh.CStruct(),
"UpdateTokenInfoScopeTwap" / borsh.CStruct(),
"UpdateTokenInfoScopeChain" / borsh.CStruct(),
"UpdateTokenInfoName" / borsh.CStruct(),
"UpdateTokenInfoPriceMaxAge" / borsh.CStruct(),
"UpdateTokenInfoTwapMaxAge" / borsh.CStruct(),
"UpdateScopePriceFeed" / borsh.CStruct(),
"UpdatePythPrice" / borsh.CStruct(),
"UpdateSwitchboardFeed" / borsh.CStruct(),
"UpdateSwitchboardTwapFeed" / borsh.CStruct(),
"UpdateBorrowRateCurve" / borsh.CStruct(),
"UpdateEntireReserveConfig" / borsh.CStruct(),
"UpdateDebtWithdrawalCap" / borsh.CStruct(),
"UpdateDepositWithdrawalCap" / borsh.CStruct(),
"DeprecatedUpdateDebtWithdrawalCapCurrentTotal" / borsh.CStruct(),
"DeprecatedUpdateDepositWithdrawalCapCurrentTotal" / borsh.CStruct(),
"UpdateBadDebtLiquidationBonusBps" / borsh.CStruct(),
"UpdateMinLiquidationBonusBps" / borsh.CStruct(),
"UpdateDeleveragingMarginCallPeriod" / borsh.CStruct(),
"UpdateBorrowFactor" / borsh.CStruct(),
"UpdateAssetTier" / borsh.CStruct(),
"UpdateElevationGroup" / borsh.CStruct(),
"UpdateDeleveragingThresholdDecreaseBpsPerDay" / borsh.CStruct(),
"DeprecatedUpdateMultiplierSideBoost" / borsh.CStruct(),
"DeprecatedUpdateMultiplierTagBoost" / borsh.CStruct(),
"UpdateReserveStatus" / borsh.CStruct(),
"UpdateFarmCollateral" / borsh.CStruct(),
"UpdateFarmDebt" / borsh.CStruct(),
"UpdateDisableUsageAsCollateralOutsideEmode" / borsh.CStruct(),
"UpdateBlockBorrowingAboveUtilizationPct" / borsh.CStruct(),
"UpdateBlockPriceUsage" / borsh.CStruct(),
"UpdateBorrowLimitOutsideElevationGroup" / borsh.CStruct(),
"UpdateBorrowLimitsInElevationGroupAgainstThisReserve" / borsh.CStruct(),
"UpdateHostFixedInterestRateBps" / borsh.CStruct(),
"UpdateAutodeleverageEnabled" / borsh.CStruct(),
"UpdateDeleveragingBonusIncreaseBpsPerDay" / borsh.CStruct(),
"UpdateProtocolOrderExecutionFee" / borsh.CStruct(),
)
