'''
    This code was AUTOGENERATED using the codama library.
    Please DO NOT EDIT THIS FILE, instead use visitors
    to add features, then rerun codama to update it.
    @see https://github.com/codama-idl/codama
'''

import borsh_construct as borsh
import typing
from construct import Container
from dataclasses import dataclass

class WithdrawalCapsJSON(typing.TypedDict):
    configCapacity: int
    currentTotal: int
    lastIntervalStartTimestamp: int
    configIntervalLengthSeconds: int

@dataclass
class WithdrawalCaps:
    layout: typing.ClassVar = borsh.CStruct(
        "configCapacity" /borsh.I64,
        "currentTotal" /borsh.I64,
        "lastIntervalStartTimestamp" /borsh.U64,
        "configIntervalLengthSeconds" /borsh.U64,
        )
    #fields
    configCapacity: int
    currentTotal: int
    lastIntervalStartTimestamp: int
    configIntervalLengthSeconds: int
    
    @classmethod
    def from_decoded(cls, obj: Container) -> "WithdrawalCaps":
        return cls(
        configCapacity=obj["configCapacity"],
        currentTotal=obj["currentTotal"],
        lastIntervalStartTimestamp=obj["lastIntervalStartTimestamp"],
        configIntervalLengthSeconds=obj["configIntervalLengthSeconds"],
        )

    def to_encodable(self) -> dict[str, typing.Any]:
        return {
                "configCapacity": self.configCapacity,
                "currentTotal": self.currentTotal,
                "lastIntervalStartTimestamp": self.lastIntervalStartTimestamp,
                "configIntervalLengthSeconds": self.configIntervalLengthSeconds,
                }

    def to_json(self) -> WithdrawalCapsJSON:
        return {
                "configCapacity": self.configCapacity,
                "currentTotal": self.currentTotal,
                "lastIntervalStartTimestamp": self.lastIntervalStartTimestamp,
                "configIntervalLengthSeconds": self.configIntervalLengthSeconds,
                }

    @classmethod
    def from_json(cls, obj: WithdrawalCapsJSON) -> "WithdrawalCaps":
        return cls(
                configCapacity=obj["configCapacity"],
                currentTotal=obj["currentTotal"],
                lastIntervalStartTimestamp=obj["lastIntervalStartTimestamp"],
                configIntervalLengthSeconds=obj["configIntervalLengthSeconds"],
        )






