'''
    This code was AUTOGENERATED using the codama library.
    Please DO NOT EDIT THIS FILE, instead use visitors
    to add features, then rerun codama to update it.
    @see https://github.com/codama-idl/codama
'''

import borsh_construct as borsh
import typing
from solders.instruction import AccountMeta, Instruction
from solders.pubkey import Pubkey as SolPubkey
from ..program_id import PROGRAM_ID
class CreatePoolArgs(typing.TypedDict):
    index:int
    baseAmountIn:int
    quoteAmountIn:int


layout = borsh.CStruct(
    "index" /borsh.U16,
    "baseAmountIn" /borsh.U64,
    "quoteAmountIn" /borsh.U64,
    )


class CreatePoolAccounts(typing.TypedDict):
    pool:SolPubkey
    globalConfig:SolPubkey
    creator:SolPubkey
    baseMint:SolPubkey
    quoteMint:SolPubkey
    lpMint:SolPubkey
    userBaseTokenAccount:SolPubkey
    userQuoteTokenAccount:SolPubkey
    userPoolTokenAccount:SolPubkey
    poolBaseTokenAccount:SolPubkey
    poolQuoteTokenAccount:SolPubkey
    systemProgram:SolPubkey
    token2022Program:SolPubkey
    baseTokenProgram:SolPubkey
    quoteTokenProgram:SolPubkey
    associatedTokenProgram:SolPubkey
    eventAuthority:SolPubkey
    program:SolPubkey

def CreatePool(
    args: CreatePoolArgs,
    accounts: CreatePoolAccounts,
    program_id: SolPubkey = PROGRAM_ID,
    remaining_accounts: typing.Optional[typing.List[AccountMeta]] = None,
) ->Instruction:
    keys: list[AccountMeta] = [
    AccountMeta(pubkey=accounts["pool"], is_signer=False, is_writable=True),
    AccountMeta(pubkey=accounts["globalConfig"], is_signer=False, is_writable=False),
    AccountMeta(pubkey=accounts["creator"], is_signer=True, is_writable=True),
    AccountMeta(pubkey=accounts["baseMint"], is_signer=False, is_writable=False),
    AccountMeta(pubkey=accounts["quoteMint"], is_signer=False, is_writable=False),
    AccountMeta(pubkey=accounts["lpMint"], is_signer=False, is_writable=True),
    AccountMeta(pubkey=accounts["userBaseTokenAccount"], is_signer=False, is_writable=True),
    AccountMeta(pubkey=accounts["userQuoteTokenAccount"], is_signer=False, is_writable=True),
    AccountMeta(pubkey=accounts["userPoolTokenAccount"], is_signer=False, is_writable=True),
    AccountMeta(pubkey=accounts["poolBaseTokenAccount"], is_signer=False, is_writable=True),
    AccountMeta(pubkey=accounts["poolQuoteTokenAccount"], is_signer=False, is_writable=True),
    AccountMeta(pubkey=accounts["systemProgram"], is_signer=False, is_writable=False),
    AccountMeta(pubkey=accounts["token2022Program"], is_signer=False, is_writable=False),
    AccountMeta(pubkey=accounts["baseTokenProgram"], is_signer=False, is_writable=False),
    AccountMeta(pubkey=accounts["quoteTokenProgram"], is_signer=False, is_writable=False),
    AccountMeta(pubkey=accounts["associatedTokenProgram"], is_signer=False, is_writable=False),
    AccountMeta(pubkey=accounts["eventAuthority"], is_signer=False, is_writable=False),
    AccountMeta(pubkey=accounts["program"], is_signer=False, is_writable=False),
    ]
    if remaining_accounts is not None:
        keys += remaining_accounts
    identifier = b"\xe9\x92\xd1\x8e\xcf\x68\x40\xbc"
    encoded_args = layout.build({
        "index":args["index"],
        "baseAmountIn":args["baseAmountIn"],
        "quoteAmountIn":args["quoteAmountIn"],
       })
    data = identifier + encoded_args
    return Instruction(program_id,data,keys)


def find_Pool(index: , creator: SolPubkey, baseMint: SolPubkey, quoteMint: SolPubkey) -> typing.Tuple[SolPubkey, int]:
    seeds = [
       b"\x70\x6f\x6f\x6c",
       ,
       bytes(creator),
       bytes(baseMint),
       bytes(quoteMint),
    ]

    address, bump = SolPubkey.find_program_address(seeds,
        PROGRAM_ID
            )

    return address, bump



def find_LpMint(pool: SolPubkey) -> typing.Tuple[SolPubkey, int]:
    seeds = [
       b"\x70\x6f\x6f\x6c\x5f\x6c\x70\x5f\x6d\x69\x6e\x74",
       bytes(pool),
    ]

    address, bump = SolPubkey.find_program_address(seeds,
        PROGRAM_ID
            )

    return address, bump



def find_UserPoolTokenAccount(creator: SolPubkey, token2022Program: SolPubkey, lpMint: SolPubkey) -> typing.Tuple[SolPubkey, int]:
    seeds = [
       bytes(creator),
       bytes(token2022Program),
       bytes(lpMint),
    ]

    address, bump = SolPubkey.find_program_address(seeds,
            program_id=SolPubkey.from_string('ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL')
            )

    return address, bump



def find_PoolBaseTokenAccount(pool: SolPubkey, baseTokenProgram: SolPubkey, baseMint: SolPubkey) -> typing.Tuple[SolPubkey, int]:
    seeds = [
       bytes(pool),
       bytes(baseTokenProgram),
       bytes(baseMint),
    ]

    address, bump = SolPubkey.find_program_address(seeds,
            program_id=SolPubkey.from_string('ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL')
            )

    return address, bump



def find_PoolQuoteTokenAccount(pool: SolPubkey, quoteTokenProgram: SolPubkey, quoteMint: SolPubkey) -> typing.Tuple[SolPubkey, int]:
    seeds = [
       bytes(pool),
       bytes(quoteTokenProgram),
       bytes(quoteMint),
    ]

    address, bump = SolPubkey.find_program_address(seeds,
            program_id=SolPubkey.from_string('ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL')
            )

    return address, bump









def find_EventAuthority() -> typing.Tuple[SolPubkey, int]:
    seeds = [
       b"\x5f\x5f\x65\x76\x65\x6e\x74\x5f\x61\x75\x74\x68\x6f\x72\x69\x74\x79",
    ]

    address, bump = SolPubkey.find_program_address(seeds,
        PROGRAM_ID
            )

    return address, bump



