'''
    This code was AUTOGENERATED using the codama library.
    Please DO NOT EDIT THIS FILE, instead use visitors
    to add features, then rerun codama to update it.
    @see https://github.com/codama-idl/codama
'''

import borsh_construct as borsh
import typing
from anchorpy.borsh_extension import BorshPubkey
from solders.instruction import AccountMeta, Instruction
from solders.pubkey import Pubkey as SolPubkey
from ..program_id import PROGRAM_ID
class UpdateFeeConfigArgs(typing.TypedDict):
    lpFeeBasisPoints:int
    protocolFeeBasisPoints:int
    protocolFeeRecipients:list[SolPubkey]


layout = borsh.CStruct(
    "lpFeeBasisPoints" /borsh.U64,
    "protocolFeeBasisPoints" /borsh.U64,
    "protocolFeeRecipients" /BorshPubkey[8],
    )


class UpdateFeeConfigAccounts(typing.TypedDict):
    admin:SolPubkey
    globalConfig:SolPubkey
    eventAuthority:SolPubkey
    program:SolPubkey

def UpdateFeeConfig(
    args: UpdateFeeConfigArgs,
    accounts: UpdateFeeConfigAccounts,
    program_id: SolPubkey = PROGRAM_ID,
    remaining_accounts: typing.Optional[typing.List[AccountMeta]] = None,
) ->Instruction:
    keys: list[AccountMeta] = [
    AccountMeta(pubkey=accounts["admin"], is_signer=True, is_writable=False),
    AccountMeta(pubkey=accounts["globalConfig"], is_signer=False, is_writable=True),
    AccountMeta(pubkey=accounts["eventAuthority"], is_signer=False, is_writable=False),
    AccountMeta(pubkey=accounts["program"], is_signer=False, is_writable=False),
    ]
    if remaining_accounts is not None:
        keys += remaining_accounts
    identifier = b"\x68\xb8\x67\xf2\x58\x97\x6b\x14"
    encoded_args = layout.build({
        "lpFeeBasisPoints":args["lpFeeBasisPoints"],
        "protocolFeeBasisPoints":args["protocolFeeBasisPoints"],
        "protocolFeeRecipients":,
       })
    data = identifier + encoded_args
    return Instruction(program_id,data,keys)


def find_EventAuthority() -> typing.Tuple[SolPubkey, int]:
    seeds = [
       b"\x5f\x5f\x65\x76\x65\x6e\x74\x5f\x61\x75\x74\x68\x6f\x72\x69\x74\x79",
    ]

    address, bump = SolPubkey.find_program_address(seeds,
        PROGRAM_ID
            )

    return address, bump



