'''
    This code was AUTOGENERATED using the codama library.
    Please DO NOT EDIT THIS FILE, instead use visitors
    to add features, then rerun codama to update it.
    @see https://github.com/codama-idl/codama
'''

import borsh_construct as borsh
import typing
from anchorpy.borsh_extension import BorshPubkey
from anchorpy.error import AccountInvalidDiscriminator
from anchorpy.utils.rpc import get_multiple_accounts
from dataclasses import dataclass
from solana.rpc.async_api import AsyncClient
from solana.rpc.commitment import Commitment
from solders.pubkey import Pubkey as SolPubkey
from ..program_id import PROGRAM_ID


class ReferrerStateJSON(typing.TypedDict):
    shortUrl: str
    owner: str

@dataclass
class ReferrerState:
    #fields
    shortUrl: SolPubkey
    owner: SolPubkey

    discriminator: typing.ClassVar = b"\xc2\x51\xd9\x67\x0c\x13\x0c\x42"
    DISCRIMINATOR_SIZE: int = 8

    layout: typing.ClassVar = borsh.CStruct(
        "shortUrl" /BorshPubkey,
        "owner" /BorshPubkey,
        )



    @classmethod
    async def fetch(
        cls,
        conn: AsyncClient,
        address: SolPubkey,
        commitment: typing.Optional[Commitment] = None,
        program_id: SolPubkey = PROGRAM_ID,
    ) -> typing.Optional["ReferrerState"]:
        resp = await conn.get_account_info(address, commitment=commitment)
        info = resp.value
        if info is None:
            return None
        if info.owner != program_id:
            raise ValueError("Account does not belong to this program")
        bytes_data = info.data
        return cls.decode(bytes_data)

    @classmethod
    async def fetch_multiple(
        cls,
        conn: AsyncClient,
        addresses: list[SolPubkey],
        commitment: typing.Optional[Commitment] = None,
        program_id: SolPubkey = PROGRAM_ID,
    ) -> typing.List[typing.Optional["ReferrerState"]]:
        infos = await get_multiple_accounts(conn, addresses, commitment=commitment)
        res: typing.List[typing.Optional["ReferrerState"]] = []
        for info in infos:
            if info is None:
                res.append(None)
                continue
            if info.account.owner != program_id:
                raise ValueError("Account does not belong to this program")
            res.append(cls.decode(info.account.data))
        return res

    @classmethod
    def decode(cls, data: bytes) -> "ReferrerState":
        if data[:cls.DISCRIMINATOR_SIZE] != cls.discriminator:
            raise AccountInvalidDiscriminator(
                "The discriminator for this account is invalid"
            )
        dec = ReferrerState.layout.parse(data[cls.DISCRIMINATOR_SIZE:])
        return cls(
                shortUrl=dec.shortUrl,
                owner=dec.owner,
                )

    def to_json(self) -> ReferrerStateJSON:
        return {
                "shortUrl": str(self.shortUrl),
                "owner": str(self.owner),
                }

    @classmethod
    def from_json(cls, obj: ReferrerStateJSON) -> "ReferrerState":
        return cls(
                shortUrl=SolPubkey.from_string(obj["shortUrl"]),
                owner=SolPubkey.from_string(obj["owner"]),
                )




