'''
    This code was AUTOGENERATED using the codama library.
    Please DO NOT EDIT THIS FILE, instead use visitors
    to add features, then rerun codama to update it.
    @see https://github.com/codama-idl/codama
'''

import typing
from solders.instruction import AccountMeta, Instruction
from solders.pubkey import Pubkey as SolPubkey
from ..program_id import PROGRAM_ID

class DeleteReferrerStateAndShortUrlAccounts(typing.TypedDict):
    referrer:SolPubkey
    referrerState:SolPubkey
    shortUrl:SolPubkey
    rent:SolPubkey
    systemProgram:SolPubkey

def DeleteReferrerStateAndShortUrl(
    accounts: DeleteReferrerStateAndShortUrlAccounts,
    program_id: SolPubkey = PROGRAM_ID,
    remaining_accounts: typing.Optional[typing.List[AccountMeta]] = None,
) ->Instruction:
    keys: list[AccountMeta] = [
    AccountMeta(pubkey=accounts["referrer"], is_signer=True, is_writable=True),
    AccountMeta(pubkey=accounts["referrerState"], is_signer=False, is_writable=True),
    AccountMeta(pubkey=accounts["shortUrl"], is_signer=False, is_writable=True),
    AccountMeta(pubkey=accounts["rent"], is_signer=False, is_writable=False),
    AccountMeta(pubkey=accounts["systemProgram"], is_signer=False, is_writable=False),
    ]
    if remaining_accounts is not None:
        keys += remaining_accounts
    identifier = b"\x99\xb9\x63\x1c\xe4\xb3\xbb\x96"
    encoded_args = b""
    data = identifier + encoded_args
    return Instruction(program_id,data,keys)






