'''
    This code was AUTOGENERATED using the codama library.
    Please DO NOT EDIT THIS FILE, instead use visitors
    to add features, then rerun codama to update it.
    @see https://github.com/codama-idl/codama
'''

import borsh_construct as borsh
import typing
from solders.instruction import AccountMeta, Instruction
from solders.pubkey import Pubkey as SolPubkey
from ..program_id import PROGRAM_ID
class DepositObligationCollateralArgs(typing.TypedDict):
    collateralAmount:int


layout = borsh.CStruct(
    "collateralAmount" /borsh.U64,
    )


class DepositObligationCollateralAccounts(typing.TypedDict):
    owner:SolPubkey
    obligation:SolPubkey
    lendingMarket:SolPubkey
    depositReserve:SolPubkey
    reserveDestinationCollateral:SolPubkey
    userSourceCollateral:SolPubkey
    tokenProgram:SolPubkey
    instructionSysvarAccount:SolPubkey

def DepositObligationCollateral(
    args: DepositObligationCollateralArgs,
    accounts: DepositObligationCollateralAccounts,
    program_id: SolPubkey = PROGRAM_ID,
    remaining_accounts: typing.Optional[typing.List[AccountMeta]] = None,
) ->Instruction:
    keys: list[AccountMeta] = [
    AccountMeta(pubkey=accounts["owner"], is_signer=True, is_writable=False),
    AccountMeta(pubkey=accounts["obligation"], is_signer=False, is_writable=True),
    AccountMeta(pubkey=accounts["lendingMarket"], is_signer=False, is_writable=False),
    AccountMeta(pubkey=accounts["depositReserve"], is_signer=False, is_writable=True),
    AccountMeta(pubkey=accounts["reserveDestinationCollateral"], is_signer=False, is_writable=True),
    AccountMeta(pubkey=accounts["userSourceCollateral"], is_signer=False, is_writable=True),
    AccountMeta(pubkey=accounts["tokenProgram"], is_signer=False, is_writable=False),
    AccountMeta(pubkey=accounts["instructionSysvarAccount"], is_signer=False, is_writable=False),
    ]
    if remaining_accounts is not None:
        keys += remaining_accounts
    identifier = b"\x6c\xd1\x04\x48\x15\x16\x76\x85"
    encoded_args = layout.build({
        "collateralAmount":args["collateralAmount"],
       })
    data = identifier + encoded_args
    return Instruction(program_id,data,keys)






