'''
    This code was AUTOGENERATED using the codama library.
    Please DO NOT EDIT THIS FILE, instead use visitors
    to add features, then rerun codama to update it.
    @see https://github.com/codama-idl/codama
'''

import borsh_construct as borsh
import typing
from solders.instruction import AccountMeta, Instruction
from solders.pubkey import Pubkey as SolPubkey
from ..program_id import PROGRAM_ID
class DepositReserveLiquidityArgs(typing.TypedDict):
    liquidityAmount:int


layout = borsh.CStruct(
    "liquidityAmount" /borsh.U64,
    )


class DepositReserveLiquidityAccounts(typing.TypedDict):
    owner:SolPubkey
    reserve:SolPubkey
    lendingMarket:SolPubkey
    lendingMarketAuthority:SolPubkey
    reserveLiquidityMint:SolPubkey
    reserveLiquiditySupply:SolPubkey
    reserveCollateralMint:SolPubkey
    userSourceLiquidity:SolPubkey
    userDestinationCollateral:SolPubkey
    collateralTokenProgram:SolPubkey
    liquidityTokenProgram:SolPubkey
    instructionSysvarAccount:SolPubkey

def DepositReserveLiquidity(
    args: DepositReserveLiquidityArgs,
    accounts: DepositReserveLiquidityAccounts,
    program_id: SolPubkey = PROGRAM_ID,
    remaining_accounts: typing.Optional[typing.List[AccountMeta]] = None,
) ->Instruction:
    keys: list[AccountMeta] = [
    AccountMeta(pubkey=accounts["owner"], is_signer=True, is_writable=False),
    AccountMeta(pubkey=accounts["reserve"], is_signer=False, is_writable=True),
    AccountMeta(pubkey=accounts["lendingMarket"], is_signer=False, is_writable=False),
    AccountMeta(pubkey=accounts["lendingMarketAuthority"], is_signer=False, is_writable=False),
    AccountMeta(pubkey=accounts["reserveLiquidityMint"], is_signer=False, is_writable=False),
    AccountMeta(pubkey=accounts["reserveLiquiditySupply"], is_signer=False, is_writable=True),
    AccountMeta(pubkey=accounts["reserveCollateralMint"], is_signer=False, is_writable=True),
    AccountMeta(pubkey=accounts["userSourceLiquidity"], is_signer=False, is_writable=True),
    AccountMeta(pubkey=accounts["userDestinationCollateral"], is_signer=False, is_writable=True),
    AccountMeta(pubkey=accounts["collateralTokenProgram"], is_signer=False, is_writable=False),
    AccountMeta(pubkey=accounts["liquidityTokenProgram"], is_signer=False, is_writable=False),
    AccountMeta(pubkey=accounts["instructionSysvarAccount"], is_signer=False, is_writable=False),
    ]
    if remaining_accounts is not None:
        keys += remaining_accounts
    identifier = b"\xa9\xc9\x1e\x7e\x06\xcd\x66\x44"
    encoded_args = layout.build({
        "liquidityAmount":args["liquidityAmount"],
       })
    data = identifier + encoded_args
    return Instruction(program_id,data,keys)




