'''
    This code was AUTOGENERATED using the codama library.
    Please DO NOT EDIT THIS FILE, instead use visitors
    to add features, then rerun codama to update it.
    @see https://github.com/codama-idl/codama
'''

import borsh_construct as borsh
import typing
from anchorpy.borsh_extension import BorshPubkey
from solders.instruction import AccountMeta, Instruction
from solders.pubkey import Pubkey as SolPubkey
from ..program_id import PROGRAM_ID
class InitUserMetadataArgs(typing.TypedDict):
    userLookupTable:SolPubkey


layout = borsh.CStruct(
    "userLookupTable" /BorshPubkey,
    )


class InitUserMetadataAccounts(typing.TypedDict):
    owner:SolPubkey
    feePayer:SolPubkey
    userMetadata:SolPubkey
    referrerUserMetadata:SolPubkey
    rent:SolPubkey
    systemProgram:SolPubkey

def InitUserMetadata(
    args: InitUserMetadataArgs,
    accounts: InitUserMetadataAccounts,
    program_id: SolPubkey = PROGRAM_ID,
    remaining_accounts: typing.Optional[typing.List[AccountMeta]] = None,
) ->Instruction:
    keys: list[AccountMeta] = [
    AccountMeta(pubkey=accounts["owner"], is_signer=True, is_writable=False),
    AccountMeta(pubkey=accounts["feePayer"], is_signer=True, is_writable=True),
    AccountMeta(pubkey=accounts["userMetadata"], is_signer=False, is_writable=True),
    AccountMeta(pubkey=accounts["referrerUserMetadata"], is_signer=False, is_writable=False),
    AccountMeta(pubkey=accounts["rent"], is_signer=False, is_writable=False),
    AccountMeta(pubkey=accounts["systemProgram"], is_signer=False, is_writable=False),
    ]
    if remaining_accounts is not None:
        keys += remaining_accounts
    identifier = b"\x75\xa9\xb0\x45\xc5\x17\x0f\xa2"
    encoded_args = layout.build({
        "userLookupTable":args["userLookupTable"],
       })
    data = identifier + encoded_args
    return Instruction(program_id,data,keys)








