'''
    This code was AUTOGENERATED using the codama library.
    Please DO NOT EDIT THIS FILE, instead use visitors
    to add features, then rerun codama to update it.
    @see https://github.com/codama-idl/codama
'''

import borsh_construct as borsh
import typing
from solders.instruction import AccountMeta, Instruction
from solders.pubkey import Pubkey as SolPubkey
from ..program_id import PROGRAM_ID
class MarkObligationForDeleveragingArgs(typing.TypedDict):
    autodeleverageTargetLtvPct:int


layout = borsh.CStruct(
    "autodeleverageTargetLtvPct" /borsh.U8,
    )


class MarkObligationForDeleveragingAccounts(typing.TypedDict):
    riskCouncil:SolPubkey
    obligation:SolPubkey
    lendingMarket:SolPubkey

def MarkObligationForDeleveraging(
    args: MarkObligationForDeleveragingArgs,
    accounts: MarkObligationForDeleveragingAccounts,
    program_id: SolPubkey = PROGRAM_ID,
    remaining_accounts: typing.Optional[typing.List[AccountMeta]] = None,
) ->Instruction:
    keys: list[AccountMeta] = [
    AccountMeta(pubkey=accounts["riskCouncil"], is_signer=True, is_writable=False),
    AccountMeta(pubkey=accounts["obligation"], is_signer=False, is_writable=True),
    AccountMeta(pubkey=accounts["lendingMarket"], is_signer=False, is_writable=False),
    ]
    if remaining_accounts is not None:
        keys += remaining_accounts
    identifier = b"\xa4\x23\xb6\x13\x00\x74\xf3\x7f"
    encoded_args = layout.build({
        "autodeleverageTargetLtvPct":args["autodeleverageTargetLtvPct"],
       })
    data = identifier + encoded_args
    return Instruction(program_id,data,keys)



