'''
    This code was AUTOGENERATED using the codama library.
    Please DO NOT EDIT THIS FILE, instead use visitors
    to add features, then rerun codama to update it.
    @see https://github.com/codama-idl/codama
'''

import typing
from solders.instruction import AccountMeta, Instruction
from solders.pubkey import Pubkey as SolPubkey
from ..program_id import PROGRAM_ID

class RedeemFeesAccounts(typing.TypedDict):
    reserve:SolPubkey
    reserveLiquidityMint:SolPubkey
    reserveLiquidityFeeReceiver:SolPubkey
    reserveSupplyLiquidity:SolPubkey
    lendingMarket:SolPubkey
    lendingMarketAuthority:SolPubkey
    tokenProgram:SolPubkey

def RedeemFees(
    accounts: RedeemFeesAccounts,
    program_id: SolPubkey = PROGRAM_ID,
    remaining_accounts: typing.Optional[typing.List[AccountMeta]] = None,
) ->Instruction:
    keys: list[AccountMeta] = [
    AccountMeta(pubkey=accounts["reserve"], is_signer=False, is_writable=True),
    AccountMeta(pubkey=accounts["reserveLiquidityMint"], is_signer=False, is_writable=False),
    AccountMeta(pubkey=accounts["reserveLiquidityFeeReceiver"], is_signer=False, is_writable=True),
    AccountMeta(pubkey=accounts["reserveSupplyLiquidity"], is_signer=False, is_writable=True),
    AccountMeta(pubkey=accounts["lendingMarket"], is_signer=False, is_writable=False),
    AccountMeta(pubkey=accounts["lendingMarketAuthority"], is_signer=False, is_writable=False),
    AccountMeta(pubkey=accounts["tokenProgram"], is_signer=False, is_writable=False),
    ]
    if remaining_accounts is not None:
        keys += remaining_accounts
    identifier = b"\xd7\x27\xb4\x29\xad\x2e\xf8\xdc"
    encoded_args = b""
    data = identifier + encoded_args
    return Instruction(program_id,data,keys)




