'''
    This code was AUTOGENERATED using the codama library.
    Please DO NOT EDIT THIS FILE, instead use visitors
    to add features, then rerun codama to update it.
    @see https://github.com/codama-idl/codama
'''

import borsh_construct as borsh
import typing
from solders.instruction import AccountMeta, Instruction
from solders.pubkey import Pubkey as SolPubkey
from ..program_id import PROGRAM_ID
class RefreshReservesBatchArgs(typing.TypedDict):
    skipPriceUpdates:bool


layout = borsh.CStruct(
    "skipPriceUpdates" /borsh.Bool,
    )


class RefreshReservesBatchAccounts(typing.TypedDict):
    pass

def RefreshReservesBatch(
    args: RefreshReservesBatchArgs,
    accounts: RefreshReservesBatchAccounts,
    program_id: SolPubkey = PROGRAM_ID,
    remaining_accounts: typing.Optional[typing.List[AccountMeta]] = None,
) ->Instruction:
    keys: list[AccountMeta] = [
    ]
    if remaining_accounts is not None:
        keys += remaining_accounts
    identifier = b"\x90\x6e\x1a\x67\xa2\xcc\xfc\x93"
    encoded_args = layout.build({
        "skipPriceUpdates":args["skipPriceUpdates"],
       })
    data = identifier + encoded_args
    return Instruction(program_id,data,keys)



