'''
    This code was AUTOGENERATED using the codama library.
    Please DO NOT EDIT THIS FILE, instead use visitors
    to add features, then rerun codama to update it.
    @see https://github.com/codama-idl/codama
'''

import borsh_construct as borsh
import typing
from solders.instruction import AccountMeta, Instruction
from solders.pubkey import Pubkey as SolPubkey
from ..program_id import PROGRAM_ID
class RequestElevationGroupArgs(typing.TypedDict):
    elevationGroup:int


layout = borsh.CStruct(
    "elevationGroup" /borsh.U8,
    )


class RequestElevationGroupAccounts(typing.TypedDict):
    owner:SolPubkey
    obligation:SolPubkey
    lendingMarket:SolPubkey

def RequestElevationGroup(
    args: RequestElevationGroupArgs,
    accounts: RequestElevationGroupAccounts,
    program_id: SolPubkey = PROGRAM_ID,
    remaining_accounts: typing.Optional[typing.List[AccountMeta]] = None,
) ->Instruction:
    keys: list[AccountMeta] = [
    AccountMeta(pubkey=accounts["owner"], is_signer=True, is_writable=False),
    AccountMeta(pubkey=accounts["obligation"], is_signer=False, is_writable=True),
    AccountMeta(pubkey=accounts["lendingMarket"], is_signer=False, is_writable=False),
    ]
    if remaining_accounts is not None:
        keys += remaining_accounts
    identifier = b"\x24\x77\xfb\x81\x22\xf0\x07\x93"
    encoded_args = layout.build({
        "elevationGroup":args["elevationGroup"],
       })
    data = identifier + encoded_args
    return Instruction(program_id,data,keys)



