'''
    This code was AUTOGENERATED using the codama library.
    Please DO NOT EDIT THIS FILE, instead use visitors
    to add features, then rerun codama to update it.
    @see https://github.com/codama-idl/codama
'''

import borsh_construct as borsh
import typing
from solders.instruction import AccountMeta, Instruction
from solders.pubkey import Pubkey as SolPubkey
from ..program_id import PROGRAM_ID
class SocializeLossArgs(typing.TypedDict):
    liquidityAmount:int


layout = borsh.CStruct(
    "liquidityAmount" /borsh.U64,
    )


class SocializeLossAccounts(typing.TypedDict):
    riskCouncil:SolPubkey
    obligation:SolPubkey
    lendingMarket:SolPubkey
    reserve:SolPubkey
    instructionSysvarAccount:SolPubkey

def SocializeLoss(
    args: SocializeLossArgs,
    accounts: SocializeLossAccounts,
    program_id: SolPubkey = PROGRAM_ID,
    remaining_accounts: typing.Optional[typing.List[AccountMeta]] = None,
) ->Instruction:
    keys: list[AccountMeta] = [
    AccountMeta(pubkey=accounts["riskCouncil"], is_signer=True, is_writable=False),
    AccountMeta(pubkey=accounts["obligation"], is_signer=False, is_writable=True),
    AccountMeta(pubkey=accounts["lendingMarket"], is_signer=False, is_writable=False),
    AccountMeta(pubkey=accounts["reserve"], is_signer=False, is_writable=True),
    AccountMeta(pubkey=accounts["instructionSysvarAccount"], is_signer=False, is_writable=False),
    ]
    if remaining_accounts is not None:
        keys += remaining_accounts
    identifier = b"\xf5\x4b\x5b\x00\xec\x61\x13\x03"
    encoded_args = layout.build({
        "liquidityAmount":args["liquidityAmount"],
       })
    data = identifier + encoded_args
    return Instruction(program_id,data,keys)




