'''
    This code was AUTOGENERATED using the codama library.
    Please DO NOT EDIT THIS FILE, instead use visitors
    to add features, then rerun codama to update it.
    @see https://github.com/codama-idl/codama
'''

import typing
from solders.instruction import AccountMeta, Instruction
from solders.pubkey import Pubkey as SolPubkey
from ..program_id import PROGRAM_ID

class UpdateLendingMarketOwnerAccounts(typing.TypedDict):
    lendingMarketOwnerCached:SolPubkey
    lendingMarket:SolPubkey

def UpdateLendingMarketOwner(
    accounts: UpdateLendingMarketOwnerAccounts,
    program_id: SolPubkey = PROGRAM_ID,
    remaining_accounts: typing.Optional[typing.List[AccountMeta]] = None,
) ->Instruction:
    keys: list[AccountMeta] = [
    AccountMeta(pubkey=accounts["lendingMarketOwnerCached"], is_signer=True, is_writable=False),
    AccountMeta(pubkey=accounts["lendingMarket"], is_signer=False, is_writable=True),
    ]
    if remaining_accounts is not None:
        keys += remaining_accounts
    identifier = b"\x76\xe0\x0a\x3e\xc4\xe6\xb8\x59"
    encoded_args = b""
    data = identifier + encoded_args
    return Instruction(program_id,data,keys)



