'''
    This code was AUTOGENERATED using the codama library.
    Please DO NOT EDIT THIS FILE, instead use visitors
    to add features, then rerun codama to update it.
    @see https://github.com/codama-idl/codama
'''

import borsh_construct as borsh
import typing
from solders.instruction import AccountMeta, Instruction
from solders.pubkey import Pubkey as SolPubkey
from ..program_id import PROGRAM_ID
class UpdateLendingMarketArgs(typing.TypedDict):
    mode:int
    value:list[int]


layout = borsh.CStruct(
    "mode" /borsh.U64,
    "value" /borsh.U8[72],
    )


class UpdateLendingMarketAccounts(typing.TypedDict):
    lendingMarketOwner:SolPubkey
    lendingMarket:SolPubkey

def UpdateLendingMarket(
    args: UpdateLendingMarketArgs,
    accounts: UpdateLendingMarketAccounts,
    program_id: SolPubkey = PROGRAM_ID,
    remaining_accounts: typing.Optional[typing.List[AccountMeta]] = None,
) ->Instruction:
    keys: list[AccountMeta] = [
    AccountMeta(pubkey=accounts["lendingMarketOwner"], is_signer=True, is_writable=False),
    AccountMeta(pubkey=accounts["lendingMarket"], is_signer=False, is_writable=True),
    ]
    if remaining_accounts is not None:
        keys += remaining_accounts
    identifier = b"\xd1\x9d\x35\xd2\x61\xb4\x1f\x2d"
    encoded_args = layout.build({
        "mode":args["mode"],
        "value":args["value"],
       })
    data = identifier + encoded_args
    return Instruction(program_id,data,keys)



