'''
    This code was AUTOGENERATED using the codama library.
    Please DO NOT EDIT THIS FILE, instead use visitors
    to add features, then rerun codama to update it.
    @see https://github.com/codama-idl/codama
'''

import typing
from solders.instruction import AccountMeta, Instruction
from solders.pubkey import Pubkey as SolPubkey
from ..program_id import PROGRAM_ID

class WithdrawReferrerFeesAccounts(typing.TypedDict):
    referrer:SolPubkey
    referrerTokenState:SolPubkey
    reserve:SolPubkey
    reserveLiquidityMint:SolPubkey
    reserveSupplyLiquidity:SolPubkey
    referrerTokenAccount:SolPubkey
    lendingMarket:SolPubkey
    lendingMarketAuthority:SolPubkey
    tokenProgram:SolPubkey

def WithdrawReferrerFees(
    accounts: WithdrawReferrerFeesAccounts,
    program_id: SolPubkey = PROGRAM_ID,
    remaining_accounts: typing.Optional[typing.List[AccountMeta]] = None,
) ->Instruction:
    keys: list[AccountMeta] = [
    AccountMeta(pubkey=accounts["referrer"], is_signer=True, is_writable=True),
    AccountMeta(pubkey=accounts["referrerTokenState"], is_signer=False, is_writable=True),
    AccountMeta(pubkey=accounts["reserve"], is_signer=False, is_writable=True),
    AccountMeta(pubkey=accounts["reserveLiquidityMint"], is_signer=False, is_writable=False),
    AccountMeta(pubkey=accounts["reserveSupplyLiquidity"], is_signer=False, is_writable=True),
    AccountMeta(pubkey=accounts["referrerTokenAccount"], is_signer=False, is_writable=True),
    AccountMeta(pubkey=accounts["lendingMarket"], is_signer=False, is_writable=False),
    AccountMeta(pubkey=accounts["lendingMarketAuthority"], is_signer=False, is_writable=False),
    AccountMeta(pubkey=accounts["tokenProgram"], is_signer=False, is_writable=False),
    ]
    if remaining_accounts is not None:
        keys += remaining_accounts
    identifier = b"\xab\x76\x79\xc9\xe9\x8c\x17\xe4"
    encoded_args = b""
    data = identifier + encoded_args
    return Instruction(program_id,data,keys)




